### ISSUE TITLE
Hard fork the I2P network, or design/implement a new system, or implement another existing system

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#1000]
---
**By submitting this issue, I confirm the following:**

- I have read and understood the developer guide in [kovri-docs](https://github.com/monero-project/kovri-docs).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.
---

We have gathered enough evidence over the years to finally propose this issue. Not to be taken lightly, I will present a very clear proposal and finish writing this issue *after* defcon.

The most recent of many poor decisions made by Java I2P project have proven to be the straw that broke the camel's back.

Details to come.

**Comment by janowitz** [comment]
Any updates? Can't wait to read some details...

**Comment by Hueristic** [comment]
Have been waiting on this, what is going on?

**Comment by anonimal** [comment]
NOTICE: THIS ISSUE HAS BEEN MOVED TO GitLab. Please continue the discussion there. See https://github.com/monero-project/kovri/issues/1013 for details.
