### ISSUE TITLE
AddressBook: hosts.txt overwritten as a blank file

### ISSUE THREAD

**Issue by coneiric** [monero-project/kovri#1006]
When downloading a subscription from the default publisher, the default `hosts.txt` file is overwritten with a blank file.

Until GPG verification is implemented, it is not safe to overwrite the default `hosts.txt` file, and it should be read-only.

---
**By submitting this issue, I confirm the following:**

- I have read and understood the developer guide in [kovri-docs](https://github.com/monero-project/kovri-docs).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.
---

**Comment by anonimal** [comment]
>Until GPG verification is implemented, it is not safe to overwrite the default hosts.txt file, and it should be read-only.

1. As I've said to you several times already, there is no plan to implement any PGP verification.
2. It should *not* be read-only until other subscription work is finished. Our only subscription file needs to be appropriately updated.

Note: the fix is much simpler than #1007.

**Comment by coneiric** [comment]
> As I've said to you several times already, there is no plan to implement any PGP verification

I only remember talking about this once before, apologies for not remembering that point of the conversation. Thought the intention of signing `hosts.txt` file was to verify it.

> It should not be read-only until other subscription work is finished

That's fine, I can just overwrite with the newly downloaded hosts.txt, and not worry about PGP verification.

**Comment by anonimal** [comment]
NOTICE: THIS ISSUE HAS BEEN MOVED TO GitLab. Please continue the discussion there. See https://github.com/monero-project/kovri/issues/1013 for details.
