### ISSUE TITLE
SSU Extended Options and Rekey data not handled properly

### ISSUE THREAD

**Issue by majestrate** [monero-project/kovri#101]
Looking at SSUSession I never finished handling extended options and rekey data properly.

This should be fixed.

**Comment by anonimal** [comment]
If there is an issue with what was implemented then providing more info would help save some time before looking into it. Otherwise, will close as duplicate of #16 .

**Comment by majestrate** [comment]
Yeah close as duplicate of #16

**Comment by anonimal** [comment]
@majestrate thanks.
