### ISSUE TITLE
kovri overwrites all configs on start

### ISSUE THREAD

**Issue by majestrate** [monero-project/kovri#102]
every time I restart kovri it overwrites my existing kovri.conf and tunnels.cfg

**Comment by anonimal** [comment]
Cannot reproduce. If a script or alias is running CMake before kovri, see #45.

**Comment by anonimal** [comment]
I still cannot reproduce. Not on fresh start or SIGHUP, nor doing both multiple times. I also cannot find anything in the code that would cause this.

I'll close as invalid for now but will reopen should the issue persist (provided that more information can be given).
