### ISSUE TITLE
Return correct error codes in HTTPProxy.

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#11]
Moved here from TODO.

**Comment by anonimal** [comment]
Not just error codes; HTTProxy barely works. Needs full review and improvement. Removing as minor, labeling as medium.

**Comment by anonimal** [comment]
Easy work. Un-assigning myself in case someone else wants to grab this issue before I get to it.

**Comment by anonimal** [comment]
#340

**Comment by guzzijones** [comment]
I did a bare bones fix to add the correct error codes.
It is sitting in my fixhttperrorfixex branch.
I will do some testing early this week and then a pull request.
Anonimal wanted a fix for the error codes minus unit testing and other http proxy server fixes.
I agreed that it would be good to at least have a fix for now.

**Comment by anonimal** [comment]
Great start @guzzijones, keep it up! Also, please continue to reference #11 like you did in 6abd8a7, thanks.

**Comment by anonimal** [comment]
@guzzijones I've opened #507 so you can reference/close that issue when working on non-error code HTTP proxy work. We'll keep this issue solely for error codes and we can close it once we merge your error code branch.
