### ISSUE TITLE
Review #112

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#114]
- For reasons described in #113, #112 contains crypto code outside of unit tests and needs review.
- Style cleanup: contributor was unable to run cpplint before committing.
- Contributing guide: contributor added files + named files inconsistently with the rest of the codebase.
- Since @EinMByte did not sign the merge, it cannot be guaranteed that he reviewed the merge.

**Comment by EinMByte** [comment]
I didn't sign the merge, true (sorry). I did sign the commits after that (see development), so it should be clear that I did review the merge.

Note that I chose to do most of the above things myself (rather than asking @majestrate to do them), maybe that was wrong.

**Comment by anonimal** [comment]
In the past I have also chosen to either do those things myself or ask the contributor to fix their work but, in light of recent events and after discussions with @fluffypony, we decided to open tickets to keep track of issues instead of tackling everything ourselves. This way, someone else can pickup the job if no one can get to it.
