### ISSUE TITLE
Implement I2CP server

### ISSUE THREAD

**Issue by majestrate** [monero-project/kovri#12]
From the [Java I2P Docs](https://geti2p.net/en/docs/protocol/i2cp)

>The I2P Client Protocol (I2CP) exposes a strong separation of concerns between the router and any client that wishes to communicate over the network. It enables secure and asynchronous messaging by sending and receiving messages over a single TCP socket. With I2CP, a client application tells the router who they are (their "destination"), what anonymity, reliability, and latency tradeoffs to make, and where to send messages. In turn the router uses I2CP to tell the client when any messages have arrived, and to request authorization for some tunnels to be used.

If kovri implemented an i2cp server then every application that I know of that uses i2p could be used with kovri as well with 0 changes to their code. I think that this is the API that @fluffypony is searching for / trying to (re)create. Unless I am misunderstanding ( last time I checked he wants to find a router or spawn a new one if not found )

**Comment by fluffypony** [comment]
Yup that's pretty much it. If a user has Monero, the Java router, and 5 other applications that integrate Kovri all installed they shouldn't end up with seven different router instances and overload their bandwidth:)

**Comment by anonimal** [comment]
Fantastic idea! Assigning to @majestrate per our conversion on irc2p.

**Comment by anonimal** [comment]
Marking as a major enhancement because this will be a defining feature of Kovri.

**Comment by majestrate** [comment]
I2CP needs to talk be aware of I2NP so I'm adding i2cp server to `src/core` and i2cp client to `src/client`

**Comment by anonimal** [comment]
We're devising a new API for various reasons; the biggest being to avoid the limitations of I2CP and to satisfy kovri-specific options.

**Comment by EinMByte** [comment]
Also note that our API will not be over-the-network.
It is possible that I2CP will be added as a client service at a later point in time to support those use-cases that really need it.
