### ISSUE TITLE
Meeting Agenda: Feb. 14, 2016

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#124]
#### 6pm (UTC)
- Discuss preparations for Satoshi Roundtable:
 1. Discuss cleanup of README / FAQ / CONTRIBUTING + any relevant documentation
 2. Review licensing (including print format)
 3. Discuss a CoC and establish in writing
- Discuss github automated ticket/PR responder template

#### 7pm
1. Review assigned open tickets: status, code ideas (if applicable), etc.
2. Overview of all TODOs + discuss which TODOs are ticket worthy
3. Discuss cpp-netlib and/or its URI only (https://github.com/cpp-netlib/uri/)

#### 8pm
1. Any additional meeting items
2. Schedule next meeting

---------

I'll update the agenda should anyone have any amendments.

**Comment by EinMByte** [comment]
I imagine some of us (including myself) have limited time and are mostly interested/focused on the items listed under "7PM". Would it be acceptable to attend part of the meeting?

**Comment by fluffypony** [comment]
We can swap it around and do the 7pm / 8pm bits first?

**Comment by anonimal** [comment]
@EinMByte I scheduled that part for 7pm because I remember you saying you wouldn't be able to make the meeting until then. I'm fine with shifting things around if your plans changed.

**Comment by EinMByte** [comment]
@anonimal Alright. 7PM is easier for me, indeed.

**Comment by anonimal** [comment]
Spill-over items posted in #134

**Comment by EinMByte** [comment]
Sorry, wasn't able to make it (something intervened last-minute).

**Comment by anonimal** [comment]
@EinMByte meeting log posted in #47.
