### ISSUE TITLE
Crypto: RandInRange() fails to stay within range when using signed or unsigned integers

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#130]
For example:
```cpp
int port = i2p::crypto::RandInRange<int>(9111, 30777);
```
When looped, will produce the following:
```
4835
12969
12302
-7772
-9926
-10952
6444
20583
29331
609
22397
...etc.
```
For the time being, using any unsigned int appears to be fine. We currently do not use any signed int's for ```RandInRange()``` but this issue is quite dangerous because this caveat is undocumented/(code is unfinished?) so, should we ever need signed int's with ```RandInRange()``` in critical code...

**Comment by anonimal** [comment]
```
2016-02-13 06:04:46     &anonimal       Oh my...
2016-02-13 06:04:58     &anonimal       Crypto refactor is dangerously broken, at least RandInRange().
2016-02-13 06:05:20     &anonimal       #130 is worse than I thought. Unsigned types are vulnerable (somewhat differently); and we use those everywhere.
2016-02-13 06:05:33     &anonimal       I've fixed for unsigned, testing fix for signed. Unit test made to catch both.
2016-02-13 06:06:02     &anonimal       I'll give a ~24-48 window to finish up/improve tests and triple check my fixes.
2016-02-13 06:06:15     &anonimal       It's funny how usually the small things can be the deadliest, at times a few lines at most :/
2016-02-13 06:06:48     &anonimal       Testing entropy is a whole other ball game, my biggest concern being how instantiaion is handled by multithreading. Even if it appears to be fine (as did RandInRange()), it may not be - and needs more review/work.
2016-02-13 06:07:06     &anonimal       Ultimately, we'll never need signed for any ranges but if the purpose of the refactor was to make things easier and flexible, then this abstraction needs more work.
2016-02-13 06:07:30     &anonimal       Any dev shouldn't have to keep such tight track of which types they use for a simple random range of digits (and unsigned didn't work well anyway).
2016-02-13 06:08:20     &anonimal       fluffypony: I seriously think we should ask all future contributors to *include* unit-tests with any new "features" they wish to implement; including mission-critical/sensitive refactors. Any PR's that lack a unit test should sit in a PR'able state until a test is made by either side, IMHO.
2016-02-13 06:08:42     &anonimal       EinMByte knows what he's doing and he's already included great tests with his refactor, so I'm not worried about that.
2016-02-13 06:09:01     &anonimal       Anyway, aren't unit-tests w/ new features a standard fork/pull methodology by now?
```

**Comment by EinMByte** [comment]
I agree that new code should always include unit tests from now on, at least when the code can be reasonably tested.

**Comment by EinMByte** [comment]
We could be reusing components from the standard library here: we could write our own generator engine.

For testing RNGs, we should consider the tests [here](http://csrc.nist.gov/groups/ST/toolkit/rng/documents/nissc-paper.pdf).

**Comment by anonimal** [comment]
@EinMByte strange, I'm not getting emails from people's comments lately (I just now saw your comment after PR'ing). Perfect timing though :smile: 

JFTR: what's not in 9c330cb are my original fixes for this ticket which were actually hacks to fix the *original* hack that was ```RandInRange()```. After realizing the futility of home-brewed discrete probability distribution solutions, STL came to the rescue and triumphed over all previous hacks/patches!

Now, if Kovri wishes to implement *only* an 0 to upperbound range, we should consider rewriting this abstraction or simply abstracting our crypto-library's range function (example: Crypto++ ```GenerateWord32()```) otherwise, the solution we currently have appears to work more than fine (see unit test).

I'm still considering your comment and open to ideas.

**Comment by EinMByte** [comment]
See also my comments on PR #132.
Basically, using (but not actually using) the Mersenne twister is confusing, and someone might just decide to use it twice (which would be insecure). I think we should write our own engine.

**Comment by anonimal** [comment]
Twice or >= 624?

I'll concede to an engine swapout but what's wrong with STL (or are you throwing in stdlib with STL)?

@EinMByte I think we should also reconsider the direction that the crypto refactor was heading toward because I'm not satisfied with where it was going. I'll add a note in #134 for us to bounce around some new ideas if you're able to make the next meeting.

**Comment by EinMByte** [comment]
@anonimal Twice was of course somewhat exaggerated, but you get the point :). With stdlib I am referring to all of the C++ standard library (STL is a subset). Sorry for not making the meeting...

**Comment by anonimal** [comment]
#### Re: STL

AFAICT, there aren't any out-of-box STL engines that suit our needs; at least not without without a fair amount of work to ensure CS.

```bash
$ git diff if-only-it-were-a-perfect-world.patch:
```
```cpp
diff --git a/src/core/crypto/Rand.h b/src/core/crypto/Rand.h
index ef11221..afced00 100644
--- a/src/core/crypto/Rand.h
+++ b/src/core/crypto/Rand.h
@@ -70,9 +75,10 @@ namespace crypto {
   /// @return  : random number in range [x, y]
   template<class T>
   T RandInRange(T x, T y) {
-    std::mt19937 mte(Rand<T>());
+    T seed = Rand<T>();
+    std::default_random_engine eng(seed);
     std::uniform_int_distribution<T> d(x, y);
-    return d(mte);
+    return d(eng);
   }
```
leaves us with more problems than fixes:

1. Even if we guaranteed one object per thread, ```default_random_engine``` is not guaranteed CS (AFAICT).
2. If engine was not properly locked and seeded, bad seed would be shared across threads.
3. ```uniform_int_distribution``` across threads is probably not a good idea.

And nail-in-coffin:
```bash
$ grep default_random_engine /usr/include/c++/5.3.0/bits/random.h
typedef minstd_rand0 default_random_engine;
```
vs. [MSVS 2015](https://msdn.microsoft.com/en-us/library/bb982398.aspx)
```
typedef mt19937 default_random_engine;
```
#### Choices
So, I see at least two choices:

1. Spend time implementing an engine that guarantees thread safety / ensures same seed is not shared across threads after being properly seeded, etc. If new engine is better than library's than use it, otherwise; default to library.

2. Abstracting ```GenerateWord32()``` and imposing a ```(0, max)``` limit on ranges.
 - Less "sexy" then what we have because it interferes with both the aesthetic and datatype-specific goals of the current refactor but handles autoseeding and class-level multi-threading out-of-box (*sigh of relief*). Ultimately, the need for datatype specificity is turning out to be a hindrance so I would glad to see that gone and replaced with something better.
 - We currently never use a lowerbound < 0 anyway so negatives are not needed.
 - We're already using Crypto++, so let's *use* it.

#### Proposal

I propose we proceed with choice no. 2 as an adequate fix for now until we can discuss more at our next meeting or unless anyone else can provide a guaranteed CS patch/fix. 

@EinMByte: any objections or other ideas?

**Comment by EinMByte** [comment]
Seems like writing our own random engine might be somewhat problematic.
It seems that Crypto++ allows constructing `Integer` objects from a RNG: https://www.cryptopp.com/docs/ref/class_integer.html. The construct I'm looking at is

`Integer (RandomNumberGenerator &rng, const Integer &min, const Integer &max, RandomNumberType rnType=ANY, const Integer &equiv=Zero(), const Integer &mod=One())`

So what about

`return static_cast<T>(Integer(prng, Integer(x), Integer(y)).ConvertToLong());`

This should be fine as long as `T` is large enough and integral.

**Comment by anonimal** [comment]
@EinMByte great discovery. You are correct about the inefficiency though.

Here is another proposal:

This was one of my first working fixes against ac349a023b55cf1d1a52756766d41d37d2cd5722 if we had decided to choose only a ```(0, max)``` lower/upper-bound.
```diff
diff --git a/src/core/crypto/Rand.h b/src/core/crypto/Rand.h
index 446634d..54ef0cd 100644
--- a/src/core/crypto/Rand.h
+++ b/src/core/crypto/Rand.h
@@ -30,7 +30,9 @@
 
 #ifndef SRC_CORE_CRYPTO_RAND_H_
 #define SRC_CORE_CRYPTO_RAND_H_
+
 #include <cstdlib>
+#include <cinttypes>  // imaxabs()
 #include <stdexcept>
 
 namespace i2p {
@@ -59,14 +61,18 @@ namespace crypto {
   // @return random in range [min, max)
   template<class T>
   T RandInRange(T min, T max) {
-    if (min > max) {
-      throw std::logic_error("i2p::crypto::RandInRange() min <= max");
+    if ((min > max) || (max < 0)) {
+       throw std::logic_error("RandInRange(): min > max");
     } else if (min == max) {
       return min;
     }
     T dlt = max - min;
-    T ret = Rand<T>();
-    ret %= dlt;
+    // We never want a negative if T is signed
+    T ret = imaxabs(Rand<T>());
+    // If 0, use dlt
+    if (!(ret %= dlt)) {
+      ret = dlt;
+    }
     ret += min;
     return ret;
   }
```
While this is working fix, I still propose we simply do the following against https://github.com/anonimal/kovri/commit/9c330cb62c178478ead569e69563f82a25534c58:

```diff
diff --git a/src/core/crypto/Rand.h b/src/core/crypto/Rand.h
index ef11221..5c538aa 100644
--- a/src/core/crypto/Rand.h
+++ b/src/core/crypto/Rand.h
@@ -32,9 +32,10 @@
 #define SRC_CORE_CRYPTO_RAND_H_
 
 #include <cstdlib>
-#include <random>
 #include <stdexcept>
 
+#include "CryptoPP_Rand.h"
+
 namespace i2p {
 namespace crypto {
 
@@ -54,25 +55,18 @@ namespace crypto {
     return ret;
   }
 
-  /// Returns a random integer of type T from a true
-  /// range of integers (either signed or unsigned).
-  ///
-  /// CAUTION: as with usual good programming practice,
-  /// if an implementer expects that x or y should meet their
-  /// lower/upper-bound requirement, they should test that
-  /// x or y is satisfied before implementing this function
-  /// (e.g., if you expect x < y but y < x, a true range will
-  /// still be produced - and your y function is likely broken).
+  /// Returns a random integer of type T
   ///
   /// @param T : integer type
-  /// @param x : assumed to be lowerbound (but not necessary)
-  /// @param y : assumed to be upperbound (but not necessary)
-  /// @return  : random number in range [x, y]
+  /// @param min : lowerbound T
+  /// @param max: upperbound T
+  /// @return : random number in range [min, max]
   template<class T>
-  T RandInRange(T x, T y) {
-    std::mt19937 mte(Rand<T>());
-    std::uniform_int_distribution<T> d(x, y);
-    return d(mte);
+  T RandInRange(T min, T max) {
+    if ((min > max) || (min < 0)) {
+      throw std::logic_error("RandInRange(): logic error");
+    }
+    return prng.GenerateWord32(min, max);
   }
 
 }  // namespace crypto
```

as prng is already internally linked and instantiated for each respective translation unit because of ```Rand()/RandBytes()``` and ```CryptoPP_Rand.h```:

```cpp
namespace i2p {
namespace crypto {

typedef CryptoPP::AutoSeededRandomPool PRNG;
static PRNG prng;

}  // namespace crypto
}  // namespace i2p
```

so the overhead of calling another method is trivial - but the maintenance for things like
```cpp
size_t ind = i2p::crypto::RandInRange<size_t>(size_t{0}, s - size_t{1});
```
to
```cpp
size_t ind = i2p::crypto::RandInRange(0, s - 1);
```
is an improvement. The only drawback I see is that we're limited to 32bit ints, but we never use 64 or floating types for ranges nor do I see needing either in the reasonable future.

How does that sound?

**Comment by EinMByte** [comment]
I think that's ok, since we don't need signed integers anyway.
If we want to support 64 bit types, we can always specialize the template function for these types.

**Comment by anonimal** [comment]
Re: ```CryptoPP_Rand.h```, assuming we keep our pImpl patter, yes, that wouldn't be ideal; but I was assuming we would be rewriting parts of that anyway.

I think what's best for now is to go with the original un-committed fix ([first patch in my previous comment](https://github.com/monero-project/kovri/issues/130#issuecomment-184812506)) and elaborate more on implementation options at our next meeting. Either abstracting within an abstraction or a one-size-fits-all allocation (all for a simple range) IMHO seems like a bit much, but do I acknowledge and understand/appreciate the virtue of doing either/or.

**Comment by EinMByte** [comment]
I think we should definitely keep pimpl for crypto. It has the advantage that we can swap out Crypto++ (if we would want to do that in the future). Should also save us a lot of compilation time.
