### ISSUE TITLE
Meeting Agenda: *Saturday* Mar. 5th, 6pm UTC

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#134]
#### 6pm (UTC)
1. Discuss results of Satoshi Roundtable
2. ~~[from Feb. 14th meeting] Discuss github automated ticket/PR responder template and/or #143~~
[RESOLVED in #143]
3. Issues with i2pmail.org email and the importance of resolving #27 + H1 contact information
4. [Webhooks](https://developer.github.com/webhooks/) + IRC notification

#### 6:30pm
1. [from Feb. 14th meeting] Overview of all TODOs + discuss which TODOs are ticket worthy
2. [from Feb. 14th meeting] Discuss [cpp-netlib](http://cpp-netlib.org/0.11.2/in_depth.html#in-depth) and/or its [URI](https://github.com/cpp-netlib/uri/) implementation
3. Discuss [libcurl](https://curl.haxx.se/libcurl/) as alternative to cpp-netlib
4. Discuss decaying/aging bloom filter options for #126, thoughts on [stable and A^2 C++11 bloom filters](https://github.com/mavam/libbf).
5. pImpl discussion for crypto: pros/cons, alternatives, etc.
6. Embedded certificate revocation as mentioned in #149 
7. Review assigned open tickets: status, code ideas (if applicable), etc.

#### 8pm
1. Any additional meeting items
2. Schedule next meeting

---------

I'll update the agenda should anyone have any amendments.

**Comment by EinMByte** [comment]
Let's add a discussion of PIMPL for the crypto.

**Comment by anonimal** [comment]
Added. I imagine the 6pm agenda will be short and, if possible, I'd like to keep it short so we can start the 7pm agenda at around 6:30pm. @fluffypony @EinMByte any objections?

**Comment by fluffypony** [comment]
That's fine

**Comment by EinMByte** [comment]
@anonimal should be fine.

**Comment by anonimal** [comment]
BUMP'ing for meeting in 4 days. Added libcurl and other items since OP.

**Comment by anonimal** [comment]
Added 2 more items to 6pm agenda.  We'll have a lot to cover in two hours. I'll try to write out any thoughts I have before the meeting.

**Comment by anonimal** [comment]
Successful meeting though we missed @fluffypony. Meeting log posted in #47.
