### ISSUE TITLE
Reseed Rewrite/Refactor

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#149]
**By submitting this issue, I confirm the following:**

- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

*Place an X inside the bracket to confirm*
- [X] I confirm.

---

Working on #141 drove me crazy not because of zlib but because of the state of our reseed code. I'm proposing **at least** the following:

- [X] C++11 (minimum) refactor
- [X] Create/rewrite appropriate classes
  - Improve class Reseed
  - Create classes SU3, ZIP, X509, and HTTP
  - Refactoring: move the mess of local variables into a POD type
  - Use spec-identifiable constants instead of raw numbers
  - Move class ZIP to core/util/ZIP.{h,cpp}
  - Move class X509 to core/crypto/X509.{h,cpp}
- [X] Design rewrite
  - Create better reseed abstraction
    - See constructors, design, and interface of class Reseed/SU3/ZIP/X509
  - Separate parsing:
    - Class SU3 parsing from X.509/signature parsing and from class ZIP parsing
  - Rewrite/refactor related class NetDb code
  - Refactor: get rid of -1 return values, use bool and adjust related code
- [X] Create/implement stream abstraction
  - Stream wrapper for strongly-typed classes
- [X] Abstract CryptoPP from class ZIP and class X509. Referencing #57.
  - Pimpl ZIP decompression
  - Pimpl X.509 and separate cert processing from decoding
  - Ensure uncaught exceptions are caught
  - Cleanup pimpl-related directory structure
- [X] Feature: manual reseed: create/implement an overloaded ```--reseed-from``` run-time switch
 - Handles reseeding from file
 - Handles reseeding from specified URL
- [X] Feature: create/implement ```--reseed-skip-ssl-check``` run-time switch
  - Allows connecting to servers with certificates not shipped with
    Kovri (such as a local server)
  - Users can still put their self-signed cert in ```KOVRI_DATA_DIR/certificates/su3```
    and skip this switch if desired
- [X] HTTP: minor design refactor to accommodate new class Reseed design
  - Download function stores results in member stream, returns bool
  - HTTP response is stored in member variable
  - Logic design refactor to fix erroneous error response and help with
    debugging
- [X] Spec review
  - Ensure that SU3 implementation meets requirements and provides a
    minimal interface to implement future content-types and/or specifications
    (ex. for auto-update or news feed)
  - Ensure that ZIP meets minimum requirements for our use-case
- [X] Create secure sanity checks
- [X] Create unit tests (referencing #7)
  - Tests for class SU3, ZIP, and X509
  - Cleanup unit-test directory structure and rename appropriate files
  - Adjust CMake accordingly
- [X] Document code
  - Extensive documentation where possible
- [X] Resolve any preexisting TODO's
- [X] General improvements and rewrites
- ~~Prepare for SOCKS/PT functionality (see #150) / Abstract download mechanism~~  **Edit:** will move to new ticket once #155 is resolved
- ~~Implement all signature types~~ **Edit:** moved to #160

**Comment by EinMByte** [comment]
It's important to ensure that the tests can actually be written, so the parsing code should be well-separated.

Possibly we should be able to handle embedded certificate revocations (was recently suggested by zzz for Java I2P), but we need to look into the specifics.

**Comment by anonimal** [comment]
Yes, its been separated. I'll add embedded certificate revocation to #134, sounds interesting.

**Comment by anonimal** [comment]
I've updated the proposal and checked-off completed work. Everything proposed has been started and is in progress. I'll check-off more as it gets done.

Re-labeling the ticket as ```major``` in terms of reseed rewrite.

**Comment by anonimal** [comment]
Added two more completed additions to the proposal:
- Create/implement ```--reseed-skip-ssl-check```
- Minor HTTP design refactor to accommodate new ```Reseed``` design

HTTP will be rewritten regardless of how we resolve #155 but, at this point, it was unavoidable to deal with so I had to make the appropriate adjustments.

**Comment by anonimal** [comment]
I'm removing ```Implement all signature types``` from the proposal and will open in a new su3 signature-related ticket because of the following:
```
&anonimal str4d zzz: Hi. What is the present use-case for having 7 signatures types for su3 if every reseed server uses only 1 type (0x0006)?
+zzz anonimal, no good reaso
+zzz ^reason
&anonimal zzz: Ok, good to know. Have there been any discussions about changing the spec then?
+zzz anonimal, a while back I added some info on the common structures spec page listing the use cases for each signing key type
+zzz wouldn't hurt to add similar info to the su3 spec
+str4d anonimal, tl;dr the same Java stucture and signature code namespace was used for representing signature types
+str4d for simplicity
+str4d But the spec defines which codes are actually supported by which parts of the router
&anonimal zzz str4d: Thanks. So, in other words re: common structures and su3 spec, the choice was "it's already there so let's make them available in su3" instead of "we *need* weaker signing options in su3 so let's make them available"?
+str4d It was mostly that there was already Java infrastructure for handling SigTypes, and adding a new independent mechanism for SU3-specific types would have been a lot of additional work
+str4d And conceptually easier too, to have one code for one signature type and no other
+str4d instead of "sig type 2 means ECDSA-P384 in a Destination, but RSA-2048 in a SU3"
+str4d Easier to have unique sig types, and then specify what sig types different structures can use
+str4d possibly more open to abuse maybe - it's the OpenSSL / TLS issue of flexibility creating vulnerability - but in this case I don't think it's much of an issue, because e.g. for SU3 updates, Java I2P is the only user, and Java I2P will reject types that it doesn't expect IIRC (zzz can confirm)
&anonimal str4d: That makes complete sense, thanks.
&anonimal str4d: I guess my next question would be will: are there any plans to change default su3 signing from code 6 to code 8? I see that code 8 was added in .25 (or at least I see it now)
+str4d anonimal, AFAIK yes
+str4d It's partly why we didn't go to EdDSA in the first place - there was no defined spec for hash signing
&anonimal I'll add a note, str4d thanks for clarifying.
```
JFTR: re: "code 6 to code 8", see ```java -cp /path/to/i2p/lib/i2p.jar net.i2p.crypto.SU3File```.

**Comment by anonimal** [comment]
It's been one month, time flies! Everything is now complete except for unit tests. After that, I will do another review of completed work and then PR.

I've crossed off the item about abstracting the download mechanism because that needs its own ticket and should be addressed once we have a better view of #150 and #155. With this rewrite, we specifically use class ```HTTP``` for https downloading so, I foresee a abstraction of being of great use.

**Comment by EinMByte** [comment]
I quickly went through your latest commit, added some minor comments. Looks good so far.

**Comment by anonimal** [comment]
Thanks @EinMByte! I'll respond to the comments and make any needed corrections.
