### ISSUE TITLE
Use constant-time comparison in eddsa25519

### ISSUE THREAD

**Issue by EinMByte** [monero-project/kovri#153]
**By submitting this issue, I confirm the following:**

- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

*Place an X inside the bracket to confirm*
- [x] I confirm.

---
`crypto_verify` should be implemented as a constant-time comparison rather than by using `memcmp`.

Theoretically, this could leak (part of) the valid signature. That might allow an attacker to forge a signature.

**Comment by anonimal** [comment]
I would recommend we look into [Tor's implementation](https://gitweb.torproject.org/tor.git/tree/src/ext/ed25519/ref10/crypto_verify_32.h) as it is most likely **very** researched.

We could also easily port [str4d's implementation](https://github.com/str4d/ed25519-java/blob/ab0be28d9caf373364a6f10806a70d6428029e48/src/net/i2p/crypto/eddsa/Utils.java) but:

> Not for external use, not maintained as a public API.

and

>Disclaimer

>There are no guarantees that this is secure for all uses. All unit tests are passing, including tests against the data from the Python implementation, and the code has been reviewed by an independent developer, but it has not yet been audited by a professional cryptographer. In particular, the constant-time signing properties of ref10 may not have been completely retained (although this is the eventual goal for the Ed25519-specific implementation).

So, two questions @EinMByte:
  - Why would SUPERCOP have used ```memcmp``` to begin with? Not yet standardized?
  - Can you recommend any trustworthy/proven C implementations?

**Comment by anonimal** [comment]
Can we keep it simple and swap-out what we have with ```supercop-20141124/crypto_verify/32/ref/verify.c```?

**Comment by EinMByte** [comment]
@anonimal 
Tor's implementation should work fine, but we should probably check the optimizer does not get rid of the constant-time comparison (rather than assuming that someone else has checked this).
Answers to your first two questions:
* SUPERCOP doesn't use `memcmp`. You need to implement verify.c yourself, and as a quick solution I used `memcmp`.
* The best I can think of is: try a few implementations and check whether -O flags for various compilers don't break it.

**Comment by anonimal** [comment]
[bitmonero implements](https://github.com/monero-project/bitmonero/blob/master/src/crypto/crypto_ops_builder/verify.c) the swap-out I proposed. I'm still poking around to make sure optimizations don't break it.

I don't want to cut corners on crypto research but I also want to get things done reasonably faster. Do you have any objections to this implementation?

**Comment by EinMByte** [comment]
@anonimal Don't have any immediate objections, as long as you check that it works fine.

**Comment by anonimal** [comment]
Opened #224 for review.

- Successfully tested on Arch and Ubuntu Wily (gcc 5.2.1)
- Unit-tests and benchmarks pass for both regular and ```-DWITH_OPTIMIZE=ON``` builds
- Binary is functional with both regular and ```-DWITH_OPTIMIZE=ON``` builds. Client tunnel (IRC) is functional for both builds.
