### ISSUE TITLE
Meeting Agenda: Sunday, April 3rd, 6pm UTC

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#157]
**By submitting this issue, I confirm the following:**

- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

*Place an X inside the bracket to confirm*
- [X] I confirm.

---

#### 6pm (UTC)
~~1. [from Mar. 5th + Mar. 20th meeting] Issues with i2pmail.org email and the importance of resolving #27 + H1 contact information~~ **Edit: resolved in private. Stayed tuned to #27**
~~2. [from Mar. 5th + Mar. 20th meeting] [Webhooks](https://developer.github.com/webhooks/) + IRC notification~~  **Edit: resolved in private. No new ticket will be opened**
~~3. [from Mar. 20th meeting] Developer search~~  **Edit: opened in #159**
1. Review assigned open tickets: status, code ideas (if applicable), etc.
2. Any additional meeting items
3. Confirm next meeting schedule

**Comment by EinMByte** [comment]
I thought we agreed on 4 (6PM) in the March 20th meeting?

**Comment by anonimal** [comment]
We were awaiting your feedback since, at that time, you said you would be AFK but would check the backlog later. I'll remove the item now.

**Comment by anonimal** [comment]
Spoke to @fluffypony privately and resolved all backlogged agenda items. New agenda items welcome.

**Comment by anonimal** [comment]
JFTR: @fluffypony won't be able to make this meeting. We've agreed to meet May 1st but will also keep this date open for both myself and @EinMByte and anyone else who should wish to attend.

**Comment by anonimal** [comment]
@EinMByte is there anything you wanted to discuss in the meeting? Any status updates re: SSU?

A scheduling conflict has come up on my end so, if there isn't much or anything to discuss, then I'd like to move the meeting to May 1st instead. If you or anyone reading this wanted to discuss anything in particular, I can try to reschedule to make the meeting. If we move the meeting, I can make a note in IRC to everyone in case anyone had plans to participate tomorrow and/or we can simply move any/all ideas/topics to this ticket.

As for topics I planned on discussing, I would have reiterated what's been completed in #149 since our last meeting but, since I've been documenting its progress in-ticket, I don't see that taking up much time nor warranting a meeting.  Other than that, there's nothing else to report on my part regarding points 1 or 2. I *can* say that I do expect #149 and a handful of other tickets to be resolved by May 1st if not sooner, so that's good. As for point 3, @fluffypony is in Japan :jp: (sounds like an adventure), so a May 1st meeting date sounds reasonable (in my humble opinion).

**Comment by EinMByte** [comment]
@anonimal I agree with moving it to May 1st, I'm somewhat busy at the moment.
