### ISSUE TITLE
C++14 compliance

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#158]
**By submitting this issue, I confirm the following:**
- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

_Place an X inside the bracket to confirm_
- [X] I confirm.

---

Not only does some of this code-base not even come close to complying with C++11 standards, I've had to rewrite some of my newly written C++14 compliant code to work with C++11 (not frequently, but its happened).

I propose that we make a simple cmake adjustment and continue to work/refactor with C++14 in mind. We could do that instead of a doing a massive refactor of the entire base in one sitting. With time, everything should eventually be brought up to date.

**Comment by EinMByte** [comment]
In my opinion, we should avoid using complex C++14 features. I think many compilers are not yet C++14 compliant, and I am not convinced support for these compilers is an admissible sacrifice.
That is, unless you can convince me otherwise.

**Comment by anonimal** [comment]
>  I think many compilers are not yet C++14 compliant

???.... aside from being [ISO standard](https://isocpp.org/std/the-standard), all *relevant* modern compilers are C++14 compliant (some more than less): gcc, clang, MSVS 2015, mingw-64... A quick search will confirm this. Don't confuse C++14 with C++1z.

As for distros: Arch, Debian, and Ubuntu all **successfully** build the C++14 kovri work I'd done out-of-box. FreeBSD and Ubuntu LTS, with minor tweaking, are technically supported but there are C++14-related build issues that I haven't spent time with because I can easily implement C++11 in those areas instead (this doesn't mean that those issues are unresolvable).

So, even though I haven't used any of the more-complex features, the question is whether to keep our code in the dark or wait for others to catch up. If I get going, I don't like to be stopped and I certainly don't like that reason to be because of archaic distros (also, by the time kovri is released, all compilers will most-likely will be fully C++14-compliant :laughing:). On the other hand, temporarily removing Ubuntu LTS support will not work with our current Travis-CI coverage but that points out a bigger issue: @monero-project should consider running Jenkins or a private CI instance so we don't have to work with such tight constraints (maybe there is an instance that I'm not aware of?).

We're in a grey area because of lack of urgency to implement this ticket but we also don't want to avoid progress. Pending any new input/information, I currently see more than enough reasons to move forward.

@fluffypony can Monero provide an alternate CI solution (@EinMByte: FYI, we discussed CI in a meeting before you returned so this ticket brings up that discussion)?  If so, we should open a new ticket for that.

**Comment by anonimal** [comment]
Good news:

1. The Ubuntu LTS fix was trivial (install ```g++-5``` from PPA) and Travis-CI now [supports PPA for LTS](https://docs.travis-ci.com/user/installing-dependencies/). Re: Travis, the last I checked, PPA wasn't supported (or I overlooked it at the time, it was a while ago) so that's why I thought our coverage would be effectively broken. A quick change to ```.travis.yml``` should bring us up to speed so we don't have to abandon Travis (at least not for this ticket).

2. I whipped up a quick C++14 test and it builds/runs on OS X 10.9.5 Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn) so kovri *should* work. We're not out of the woods yet but I imagine the fix is also trivial.

That just leaves us with BSD and Windows. BSD will most likely leave us with a ports requirement but, again, trivial. As for Windows, I can spend time with the build after some more priority tickets are resolved (the Windows build needs a huge amount love as its been practically ignored since we started) but, again, I'm sure any mingw-w64 C++14-related issues will also be trivial to overcome.

**Comment by anonimal** [comment]
For now what I think is best is to stick with C++11 until I (or anyone) can guarantee and that any C++14 work will build on every currently supported platform with minimal hassle and that build instructions can be easily executed by an average user. After more priority issues are resolved, I'll reference this ticket in a C++14-related PR and we can take it from there.

**Comment by noloader** [comment]
While browsing this project's issues, this caught my eye. Crypto++ is now actively testing for C++14 issues. See [Commit 8119a03826814482](http://github.com/weidai11/cryptopp/commit/8119a038268144827a9fabb751d33d5dd22fa296).

**Comment by anonimal** [comment]
Great to know @noloader, thanks. When I find time to work on this issue, I'll be sure to report any upstream issues should they arise.

**Comment by anonimal** [comment]
I was reminded with #504 that between July and November (and before and also after), I've stopped referencing this issue for all C++11/14 refactoring and new implementation (it's just too much to keep track of).

I've opened #505 to close this issue but if non-compliance ever becomes an issue, I'll gladly re-open.
