### ISSUE TITLE
Meeting Agenda: Sunday, May 1st, 6pm UTC

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#163]
**By submitting this issue, I confirm the following:**

- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

*Place an X inside the bracket to confirm*
- [X] I confirm.

---

#### 6pm (UTC)

1. Discuss ```Get/Set``` function guideline. See https://github.com/anonimal/kovri/commit/8d63e4dba045d64dad342c32d3e205e500e76944#commitcomment-17054772
2. Discuss #48 
3. Review assigned open tickets: status, code ideas (if applicable), etc.
4. Any additional meeting items
5. Confirm next meeting schedule

**Comment by anonimal** [comment]
Meeting log in #47.

**Comment by fluffypony** [comment]
So I was thinking: is anyone against moving meetings to #monero-dev on Freenode (there's an i2p relay for the channel) and moving the time to straight after the Monero dev meeting? We hold it every two weeks, next one is [this Sunday at 16:00 UTC](http://www.timeanddate.com/worldclock/converted.html?iso=20160508T16&p1=0&p2=56&p3=37&p4=102&p5=240&p6=136&p7=179&p8=137&p9=70).

I think it will provide more eyes on Kovri development, and expose contributors to the issues faced by both sub-projects.

**Comment by anonimal** [comment]
Yes and no. Instead, I think there should simply be a channel relay ```#kovri-dev <-> #monero-dev``` for the duration of that meeting time because there are i2p dev's idling ```#kovri-dev``` that will most likely not hop over to ```#monero-dev``` for every meeting; and they do give good input.

**Comment by fluffypony** [comment]
That's a good point - can definitely set that up. So if we do it at 17:00 UTC this Sunday would that work for you? I'd suggest also rehashing anything you're unable to get to, so that newcomers can pick it up if they want to.

**Comment by anonimal** [comment]
Possibly, but I don't see a reason to meet if no one has committed to the meeting. Also, in the past 3 meetings over the past several months, people have either been extremely late - thus missing the meeting entirely - or no-shows despite having agreed to appear so, I'm not entirely motivated to show up to another one of those kinds of meetings.

As it stands, we have 48 open issues that anyone can attend to. Considering that I just held a meeting this past Sunday, I have nothing new to say that hasn't already been said so, if I show up this coming Sunday, I would only be available for questions.  Though, if that is the case, questions can be answered at anytime in ```#kovri-dev```.

I may be able to make this Sunday but if not, then I'll check the backlog to see how it went - or the log should be pasted somewhere for future reference. If the meeting goes well, then I can schedule for the 22nd.
