### ISSUE TITLE
Crypto: cleanup pimpl layout and logic + finish RNG related refactor

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#164]
**By submitting this issue, I confirm the following:**

- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

*Place an X inside the bracket to confirm*
- [X] I confirm.

---

Working on #162 pointed out the illogical layout/design of our preexisting pimpl implementation. The design should look similar to what was implemented in #162 (```ZIP``` and ```X509```).  Pending feedback, I can assign myself this ticket since the work is fresh on my mind.

Referencing #57.

**Comment by anonimal** [comment]
Rather than give a laundry list of issues, I will focus on three for this ticket and then devote any other crypto refactor work to #57: 

1. Within the realm of ```Signature``` there is still cryptopp material in the base which defeats the purpose of it being pimpl'd. Also, cleanup the various files within core/crypto that still call cryptopp headers (again, defeats the purpose of pimpl).
2. Redesign/refactor: the previous design was unnecessary in terms of organization and the logic was askew. Rewrite with maintainability in mind.
3. C++11/style guideline refactor.

I've finished most of the work and can finish the rest by this week.

**Comment by anonimal** [comment]
Added ```Finish the RNG related refactor that wasn't finished``` as a fourth issue to be resolved with this ticket.

**Comment by anonimal** [comment]
Finishing the RNG refactor required the creation of class ```DiffieHellman``` and the moving of ```CryptoConst``` into pimpl directory. The moving of ```CryptoConst``` is fine as its only used internally (though a redesign wouldn't hurt) and the creation of ```DiffieHellman``` was inevitable as it is part of #57.

This ticket is complete and I will PR this week (before the weekend) after reviewing and doing any touch-ups.

**Comment by EinMByte** [comment]
@anonimal It looks ok to me. Then again, I have only glanced over it.
