### ISSUE TITLE
OSX: build fails on linkage

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#175]
**By submitting this issue, I confirm the following:**

- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

*Place an X inside the bracket to confirm*
- [X] I confirm.

---

**Edit**: original post no longer applies when building with clang against 368bfdc.

All that remains for this ticket is https://github.com/weidai11/cryptopp/issues/232.

**Comment by anonimal** [comment]
```
anonimal | bigreddmachine: FYI regarding the link, I added -stdlib=libc++ back in December when I was more active with clang and it did fix the linkage issue.                                                            │         
anonimal | Now that I've dropped clang support for bsd/osx, that option does not exist in gcc - so we can't use it.                                                                                                       │         
anonimal | This does bring up the question of *if* we must now build respective libraries (boost/crypto++/more?) using g++-5/g++-6 and not clang.                                                                         │         
anonimal | I really hope that's not the case.
```

**Comment by rakhimov** [comment]
I doubt you can build with GCC 5 on OS X due to binary incompatibility of all dependencies,
which are likely to have been compiled with clang-llvm.

**Comment by rakhimov** [comment]
I got a working build on Travis with clang: https://travis-ci.org/rakhimov/kovri/builds/145718362

**Comment by rakhimov** [comment]
The binary incompatibility goes the other way around as well,
so with GCC 5+ on Ubuntu as default (Wily, Xenial), 
clang builds will fail to link.

**Comment by anonimal** [comment]
@rakhimov [proved that, on Travis-CI,](https://travis-ci.org/rakhimov/kovri/builds/145718362) we can still build with clang on OSX but, in our in-house OSX instance, though passing ```c++1y``` fixes the cmake issue, make will still fail for various reasons.

@monero-project @fluffypony or myself needs to review our in-house instance for discrepancies. Once that is resolved (or if we shell-out fiat for the OSX Travis build), I'd like to update the building documentation to reflect OSX clang support.
