### ISSUE TITLE
Meeting Agenda: Sunday, June 19th, 17:00 UTC

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#192]
**By submitting this issue, I confirm the following:**

- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

*Place an X inside the bracket to confirm*
- [X] I confirm.

---

#### 17:00 (UTC)

1. Greetings
2. Brief review of what's been completed since the previous meeting
3. C++ specific discussion (carried over from June 5th meeting)
4. Review open tickets (assigned and/or unassigned): status, code ideas (if applicable), etc.
5. Discuss any pertinent TODO's
6. Any additional meeting items
7. Confirm next meeting date/time

**Note: we will have meetings every two weeks in ```#monero-dev``` after the 16:00 UTC meeting. ```#kovri-dev <-> #monero-dev``` will be relayed for the duration of our meeting**

**Comment by EinMByte** [comment]
I should be able to make this meeting, and get some work done too.

**Comment by anonimal** [comment]
:+1: Looking forward to your return.
