### ISSUE TITLE
IPv6 Peer Testing

### ISSUE THREAD

**Issue by EinMByte** [monero-project/kovri#213]
**By submitting this issue, I confirm the following:**
- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

_Place an X inside the bracket to confirm_
- [X] I confirm.

---

[Proposal 126 ](http://i2p-projekt.i2p/spec/proposals/126-ipv6-peer-testing) to be added to the SSU implementation.
~~Still waiting for more details from zzz.~~ Spec on the relevant SSU pages.

Should be added after #140.

**Comment by anonimal** [comment]
Referencing #194. Must we implement by [0.9.27](https://github.com/i2p/i2p.www/commit/57a7a2b6cdcaf7d2134d6ae06d7a3dc8e9d1aab1#diff-d2763809de03e13237770f91285f9428L1072)?

**Comment by EinMByte** [comment]
@anonimal Yes, we must.

**Comment by anonimal** [comment]
From ```#kovri-dev```:
```
+zzz    anonimal, for IPv6 peer testing (proposal 126), I've updated the docs to make it optional for 0.9.27. Routers will indicate support by including (or not) the 'B' capability. See the zzz.i2p thread.
+zzz    basically this gives you more flexibility to implement it or not, while still bumping your version to 0.9.27
```
