### ISSUE TITLE
Considerations for CLA or "... claim no ownership to its content" PR nonsense

### ISSUE THREAD

**Issue by rakhimov** [monero-project/kovri#232]
**By submitting this issue, I confirm the following:**

- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

*Place an X inside the bracket to confirm*
- [x] I confirm.

---
Disclaimer: I am not a lawyer.

Contributors own their contributions and can do whatever they please to do with their own work,
e.g., contribute to other projects under different license.
If they claim no ownership to the content,
they have no right to contribute the given content
unless it is a submission on behalf of the original author
who created the content under compatible license,
e.g., getting patches from OpenOffice to LibreOffice
but not the other way around.

If Kovri asks contributors to give up their ownership rights upon contributions,
it doesn't mean that Kovri owns the code.
The contributors need to assign the copyright (e.g. FSF contributors).
A lot simpler option is to have an "inbound" license for contributors
where they agree on the license of their contributions;
that is, the code contributed to Kovri must be licensed under the current license at the time of contribution or a license that is compatible to the current one (makes updating licenses easy).

Some good contributor license agreement to adopt is Apache [ICLA](https://www.apache.org/licenses/icla.txt). Harmony ICLA is good as well.
However, note that these ICLAs deal with patents explicitly,
whereas BSD licenses don't address patents at all.

It is up to project owners to decide how to handle the contributions,
but I would at least suggest changing "... claim no ownership to its content"
to "... under the BSD 3-clause license" or something more sensible.

Edit: Added a disclaimer.

**Comment by fluffypony** [comment]
We got the checklist from here: https://github.com/daylerees/default-github-templates/blob/master/.github/PULL_REQUEST_TEMPLATE.md

I have no problem with it being amended, as the C4 dictates contributor guidelines and overrides a few tick boxes on GitHub: http://rfc.unprotocols.org/spec:1/C4/
