### ISSUE TITLE
Simplify build process

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#242]
**By submitting this issue, I confirm the following:**

- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

*Place an X inside the bracket to confirm*
- [X] I confirm.

---

Our build process could be better. bitmonero has a simpler process that will achieve the same results:

1. We move cmake and Doxyfile.in out of ./build and put into root directory
2. Root has a simple Makefile that handles cmake (similar to [here](https://github.com/monero-project/bitmonero/blob/master/Makefile))
3. ./build is created/deleted on the fly
4. We adjust doxygen/cmake/travis-ci and documentation to reflect the changes

I think this will vastly improve the build process as we won't expect users to manually switch on those lovely cmake options for every build.

**Comment by EinMByte** [comment]
I do have a lot of useful stuff in the build directory, so I'm not sure if 3 is a good idea. Probably better to only delete it if it doesn't already exist (i.e. override only the necessary files).
Other than that, go ahead.

**Comment by anonimal** [comment]
I don't think personal affections should be in ./build and nothing necessary should stay in ./build. What do you have in build that can't be moved elsewhere?

Currently, all build output (aside from Doxygen) is in ./build/debug. I can simply remove /debug as a last resort.

The work is complete except for ```make install``` (referencing #45). I'll push to my branch ```build``` before the meeting.

**Comment by EinMByte** [comment]
You're probably right about that, and everything I have there can be moved.
