### ISSUE TITLE
Create Kovri email addresses + PGP keys

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#27]
Hi @fluffypony, I'm proposing at least two points of contact:

1) A general purpose contact
- ~~-This includes being on the reseed mailing list of backup@mail.i2p~~

<b>Edit</b>: Per zzz's advice, I'll be on the mailing list since some of the messages sent are sensitive
- Media inquires and anything under "general purpose"
- Helpline if people can't use IRC

2) A security contact
- For vulnerability reports/response

<b>Edit</b>: I am currently the point of contact for VRP and we will be working on HackerOne in addition to implementing an official VRP so, once we finalize our stance, this point can be resolved. I'm not against having Monero be the point of contact so long as, within our VRP, we establish mandates for internal correspondence between Monero and VRP team (see https://trac.i2p2.de/ticket/1119).

**Comment by anonimal** [comment]
Spoke to @fluffypony, could be resolved as early as next week.

**Comment by anonimal** [comment]
```
2016-05-22 &anonimal       Moving on, #27
2016-05-22 meeting-bot     [fluffypony] ok #27 is going to have to hold for a week or two, we're busy moving email providers on getmonero.org so I'll sort it out on the new provider
```

**Comment by rakhimov** [comment]
Can we have a simple mailing list for mortals? (Google groups, for example.)
I have problems with tracking messages on Slack.
No. 1 problem is that it is synchronous.
No. 2 problem is that it doesn't show me older messages (3, 4 days seems to be a limit for free accounts.)

I am trying to catch up on the development on my spare time,
and the current setup is a bit unhelpful.

**Comment by anonimal** [comment]
I like the idea of a development mailing list but I don't think there's not enough traffic to warrant the need for one (also, we barely have github conversation traffic as it is). There's also the question of who would run and maintain any type of mailing list because Google Groups is not an option (they have the legal capacity to shut down the group if persuaded to do so).

Here are some better alternatives:

1. You can run I2P on a VPS or at home and simply connect your IRC client from there. [Java I2P](https://geti2p.net) is robust and reliable in terms of getting and staying online - and it doesn't have the pre-alpha issues we're currently dealing with. [Irc2P instructions here](https://geti2p.net/en/faq#irc)
2. If you can't run I2P, you can connect a [ZNC](http://wiki.znc.in/ZNC) instance to Freenode or OFTC so you'll never miss a conversation (the Freenode relay to Irc2P is online but we still need to bring the OFTC relay online @fluffypony)
3. If you can't run anything 24/7, contact me in private on Irc2P and I can create a ZNC account for you on my private instance. From there, the only way you could connect to the instance is through Tor - but that's easy to do and I can give quick instructions (but I would only do all of this if you know that you would be a seriously regular developer). str4d also runs a ZNC instance (IIRC) but I don't know if he has an onion service option

The bottom-line is IRC is the only real option for now but I'm open to others.

**Comment by anonimal** [comment]
From today's dev meeting:
```
@anonimal | fluffypony: ETA on domain move completion (or did you already say?... /me reads)?
@fluffypony | anonimal: by next meeting
@fluffypony | if it's done sooner then great
```
