### ISSUE TITLE
Create Kovri logo

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#282]
**By submitting this issue, I confirm the following:**
- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

_Place an X inside the bracket to confirm_
- [X] I confirm.

---

Let's hold a contest and reward with XMR or fiat. Maybe starting the contest in monero's subreddit. Referencing #216.

**Comment by anonimal** [comment]
https://99designs.com/logo-design/contests/create-beautiful-logo-kovri-privacy-enhancing-open-source-652257/brief

**Comment by fluffypony** [comment]
We have a spate of logos, please look and give feedback: https://99designs.com/logo-design/contests/create-beautiful-logo-kovri-privacy-enhancing-open-source-652257/entries

**Comment by anonimal** [comment]
Dear diary,

In [today's meeting](https://github.com/monero-project/kovri/issues/328), we agreed upon [logo 239](https://99designs.com/logo-design/contests/create-beautiful-logo-kovri-privacy-enhancing-open-source-652257/entries/239). `#monero-dev` was very active during the decision-making process and the logo was an all-around success.

We will work further with the artist to make some final changes. We also have the option to make more changes once we receive the files.

We can close this issue once we're happy with the completed product.

Yours truly,

@anonimal

**Comment by anonimal** [comment]
Note: once finalized, update the logo https://quitter.se/kovri

**Comment by anonimal** [comment]
#448 resolves this issue. I've also updated the quitter account (now we'll have to start using it 😉).
