### ISSUE TITLE
Reseed fails on OSX 10.9.5

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#320]
**By submitting this issue, I confirm the following:**

- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

*Place an X inside the bracket to confirm*
- [X] I confirm.

---

```
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.9.5
BuildVersion:   13F1911
$ clang --version
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
$ make
...
-- Boost version: 1.61.0
...
$ make install-resources
$ ./build/kovri 
Crypto: checking for AES-NI...
Crypto: AES-NI is available!
The Kovri I2P Router Project
Version 0.1.0-pre-alpha
NFO   Daemon_Singleton: initializing
NFO   Daemon_Singleton: 1 I2P client tunnels created
NFO   Daemon_Singleton: 0 I2P server tunnels created
NFO   Daemon_Singleton: listening on port 24967
NFO   Daemon_Singleton: starting NetDb
NFO   NetDb: 0 routers loaded
NFO   NetDb: 0 floodfills loaded
DBG   Reseed: processing certificates...
DBG   Reseed: acquiring signing key from "/Users/administrator/Library/Application Support/kovri/certificates/su3/atomike_at_mail.i2p.crt"
DBG   X509: successfully processed certificate
DBG   X509: successfully acquired signing key
DBG   Reseed: acquiring signing key from "/Users/administrator/Library/Application Support/kovri/certificates/su3/backup_at_mail.i2p.crt"
DBG   X509: successfully processed certificate
DBG   X509: successfully acquired signing key
DBG   Reseed: acquiring signing key from "/Users/administrator/Library/Application Support/kovri/certificates/su3/bugme_at_mail.i2p.crt"
DBG   X509: successfully processed certificate
DBG   X509: successfully acquired signing key
DBG   Reseed: acquiring signing key from "/Users/administrator/Library/Application Support/kovri/certificates/su3/echelon_at_mail.i2p.crt"
DBG   X509: successfully processed certificate
DBG   X509: successfully acquired signing key
DBG   Reseed: acquiring signing key from "/Users/administrator/Library/Application Support/kovri/certificates/su3/matt_at_drollette.com.crt"
DBG   X509: successfully processed certificate
DBG   X509: successfully acquired signing key
DBG   Reseed: acquiring signing key from "/Users/administrator/Library/Application Support/kovri/certificates/su3/meeh_at_mail.i2p.crt"
DBG   X509: successfully processed certificate
DBG   X509: successfully acquired signing key
DBG   Reseed: acquiring signing key from "/Users/administrator/Library/Application Support/kovri/certificates/su3/parg_at_mail.i2p.crt"
DBG   X509: successfully processed certificate
DBG   X509: successfully acquired signing key
DBG   Reseed: acquiring signing key from "/Users/administrator/Library/Application Support/kovri/certificates/su3/zmx_at_mail.i2p.crt"
DBG   X509: successfully processed certificate
DBG   X509: successfully acquired signing key
NFO   Reseed: successfuly loaded 8 certificates
NFO   Reseed: fetching stream from https://user.mx24.eu/i2pseeds.su3
libc++abi.dylib: terminating with uncaught exception of type std::__1::bad_function_call: std::exception
Abort trap: 6
$
```

This is new, but I've touched nothing in this area, and reseed worked ~~about~~ **Edit:** *less than a week ago (with 1107c46e0b5569abc936dd40b4802251d9ac007b)* on the same machine.  Also, unit-tests pass.

An OSX user in ```#kovri``` running ```10.12 Beta (16A304a)``` ```Apple LLVM version 7.3.0 (clang-703.0.31)``` **cannot** reproduce this issue.

Note: I've marked a TODO in uncommitted work for http/s client + options that hasn't been pushed to ```fix-305```, but testing that improvement does not yield any new result (so, the exception is unrelated). **Edit**: also, reseed is still successful on linux.

@rakhimov can you reproduce?

**Comment by rakhimov** [comment]
I don't have OSX dev platform,
and I am abusing Travis (I really feel bad about it :disappointed: )
I noticed that Travis images are linking to openssl from the OSX in usr/lib with version 0.9.+
while the brew provides 1.0+ in usr/local/opt/openssl.
I don't know if this matters for Kovri.

**Comment by rakhimov** [comment]
Travis seems to have no problems: https://travis-ci.org/monero-project/kovri/jobs/154599105
As Greg Kroah-Hartman says: "It builds, right. Ship it! Seriously!"

**Comment by anonimal** [comment]
@rakhimov lol, great quote.

I, or someone else (preferably someone else), should run this through LLDB first before looking into any potential upstream issues (I'm not ruling out upstream issues yet).

@EinMByte do you still have access to OSX (circa 10.9.5)?

**Comment by anonimal** [comment]
Side-note: downgrading to boost 1.60 has no effect (I still haven't actually debugged).

**Comment by EinMByte** [comment]
@anonimal Yes, I should be able to test this (but give me some time).

**Comment by anonimal** [comment]
```
&anonimal Interesting, very interesting: I stumbled onto a clearer picture for #320, why OSX 10.9.5 fails on reseed:
&anonimal It ultimately fails because of NetDb::CreateNetDb() but what's strange is *why*:
&anonimal Apparently all ./netDb directories are not being fully populated from what's provided in GetBase64SubstitutionTable()
&anonimal Possibly, for some strange reason, boost::filesystem::create_directory(boost::filesystem::path(directory / suffix)) is not creating *anything* that's *not* uppercase?!?!
&anonimal Strange OSX'ism? Even stranger is that this part of the code was never touched (IIRC) when this issue first arose.
&anonimal And downgrading boost had no effect.
* anonimal *huge shrug*
```

**Comment by anonimal** [comment]
Note: that the above comment occurs *once* upon fresh install and, when running kovri again, produces the original post of `Abort trap: 6`.

**Comment by anonimal** [comment]
Re: `libc++abi.dylib: terminating with uncaught exception of type std::__1::bad_function_call: std::exception`, note the following test and comments with `http.cc`:

```cpp
// Catching this block has no effect
if (!HostIsI2P()) {
  bool result = DownloadViaClearnet();   // This function is confirmed to return true (or intends to)
  LogPrint("DEBUG: result = ", result);  // <-- Yet this is never reached
  return result;
}
```
Could we be dealing with a clang bug? (I have yet to play with LLDB)

**Comment by anonimal** [comment]
JFTR: we've stopped supporting 10.9 as it is [no longer supported](https://en.wikipedia.org/wiki/OS_X_Mavericks) upstream. At present, we currently support [10.10/10.11/10.12](https://build.getmonero.org/waterfall).

**Comment by anonimal** [comment]
I cannot reproduce this reseed failure on 10.10/10.11/10.12.

As interesting as this issue is, since we no longer support 10.9 (and neither does Apple), I'm closing this ticket.
