### ISSUE TITLE
Do NOT abuse C++11 ``auto``

### ISSUE THREAD

**Issue by rakhimov** [monero-project/kovri#325]
**By submitting this issue, I confirm the following:**
- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

_Place an X inside the bracket to confirm_
- [x] I confirm.
---

I am noticing several places in Kovri database
where auto is abused and makes the code hard to read.
Please follow the reasonable suggestions from the GCSG:
https://google.github.io/styleguide/cppguide.html#auto

Some suggestions to improve the readability with auto:
- Do not use `auto` for non-local var types.
- Don't make readers do and remember template type deduction in their heads.
- Do not omit `*` and `&` from the auto type of pointers and references.

**Comment by EinMByte** [comment]
Instead, we should use `auto` whenever convenient.

**Comment by rakhimov** [comment]
Abuse of ``auto`` obfuscates the code,
and make you use your precious 7 registers of your brain.

**Comment by rakhimov** [comment]
Reading through the code I have no idea what those abused ``auto`` mean.
I have to stop and think what the function return types are.
Find a function and remember -> move on.
The code should be written for readers.

**Comment by rakhimov** [comment]
It is best to use ``auto`` when:
1. the type is super-obvious to a reader (repetitions)
2. you-really-shouldn't-care about the type (e.g. iterators)
3. it is impossible to find the type without compiler help (templates, return type deduction).

**Comment by anonimal** [comment]
Or simply look at the header: that's what they're there for (no memorization required). Or use a decent IDE (e.g., netbeans).

>The code should be written for readers.

Exactly.

>```auto``` obfuscates the code

I think it abstracts more than obfuscates.

>Do not use auto for file-scope or namespace-scope variables, or for class members

For this code-base, I disagree with their decision.

I think that once you spend a little time with this base, you'll get into the swing of things and see that the changes you proposed may actually be counterproductive in the long run.

**Comment by rakhimov** [comment]
I strongly disagree with the current Kovri practice for ``auto``.
My editor of choice is Vim,
and I learned from practice that if your codebase needs an IDE, that is a sign of a problem.
Jumping back-and-forth between declaration and usage is rather anti-reader.
Consider yourself hunting for bugs and spending a ton of your time doing template type deduction in your head.
As many features of C++, ``auto`` is powerful (makes it almost like Python),
but it should be used with care.

**Comment by EinMByte** [comment]
@rakhimov I also use vim, and `auto` should not be an issue. One of the goals of `auto` is exactly to _hide_ the type of an object in situations where it would be cumbersome to write it or where it is not relevant for the reader.

I do agree with your point "Do not omit * and & from the auto type of pointers and references.", though.

**Comment by rakhimov** [comment]
@EinMByte I can't take lazyness to type or save-some-chars as a justification for auto. I don't think the main purpose of ``auto`` is to hide anything. It is to get rid of a lot of redundancies in a statically typed (verbose) language.

If you really need to hide (or it's impossible to know the type), your intention must be explicit.
Great example for this is generic template code,
where auto makes life a lot easier than before.

**Comment by anonimal** [comment]
>and I learned from practice that if your codebase needs an IDE, that is a sign of a problem.

@rakhimov it doesn't *need* an IDE, my editor of choice is also vim (I was merely giving an argument).

>but it should be used with care.

That's subjective and I still don't agree with google on everything.

We can also consider keeping this issue a wildcard, meaning; to each his own. I really don't feel like enforcing but *even with vim* I don't have a problem following the code (even when I was new), so maybe this issue is a per-user-issue so it should not be enforced globally. Up for debate.

**Comment by rakhimov** [comment]
More guidelines to be careful with ``auto``:
http://wiki.qt.io/Coding_Conventions#auto_Keyword
http://llvm.org/docs/CodingStandards.html#use-auto-type-deduction-to-make-code-more-readable

**Comment by EinMByte** [comment]
@rakhimov I think we can agree with the LLVM standard:

> Don’t “almost always” use auto, but do use auto with initializers like cast<Foo>(...) or other places where the type is already obvious from the context.

What is "obvious" depends on the context, of course.

**Comment by anonimal** [comment]
To me, those 2 lines in #326 were obvious.

**Comment by rakhimov** [comment]
As much as I hate to admit,
there are at least two C++ gurus (Herb Sutter and Scott Meyers)
who advocate for "almost-always-auto".

Probably, the term and credo are originated from Herb Sutter's [blogpost](https://herbsutter.com/2013/08/12/gotw-94-solution-aaa-style-almost-always-auto/).

Scott Meyers has a whole 2nd chapter (2 items)
 in his "Effective Modern C++" dedicated to ``auto``.
The abstract states:

> In concept, auto is as simple as simple can be, but it’s more subtle than it looks.
Using it saves typing, sure, but it also prevents correctness and performance issues
that can bedevil manual type declarations. Furthermore, some of auto’s type deduction results,
while dutifully conforming to the prescribed algorithm, are, from the
perspective of a programmer, just wrong. When that’s the case, it’s important to
know how to guide auto to the right answer, because falling back on manual type
declarations is an alternative that’s often best avoided.

Even though I have a huge respect to these prominent authors,
I do not think the "almost-always-auto" credo
promoted by them is sound
for reasons similar to those stated in Google, LLVM, and Qt coding conventions.

Moreover, I would like to add that one of the strengths of statically typed language as C++
as compared to a dynamically typed language like Python
is that "type" is part of the contract and correctness
whether it is function signature or return type.
I don't like loosing this strong static contracts
for the sake of being generic or general by default as Python.
Think of all horrible unit tests in Python just to make sure that the right types are passed and returned
as stated in the doc.
Even Python 3 is moving towards explicit typing ([gradual typing](https://www.python.org/dev/peps/pep-0484/)).

At last, I would like to point out authors' common shortcomings
that may have influenced their arguments:

    1. They are Windows people.
    2. They are IDE folks.
    3. They are not OSS developers. (Sutter is an architect, while Meyers is a language lawyer.)

>P.S. I am terribly sorry if I offended anyone or missed some crucial information.

**Comment by anonimal** [comment]
No one is talking about how `auto` reduces refactor time, so that is to be considered as well, e.g., the argument in #326 is under the assumption that the returned type will *always* be of that type. I do agree though to `not omit * and & from the auto type of pointers and references` when possible.

In the future, if more time is spent arguing about results rather than getting results, then I think these types of arguments may not be very fruitful. Arguments will also carry more weight by anyone who is actively involved in a project (that's universal, nothing unique about that here).

From now on, we should *lean* toward using whatever style guide is in place (currently, that's our local guide which supplements/inherits google's), that way, if arguments arise in the future, we can always *point to the guide*.

**Comment by rakhimov** [comment]
Some good reads/info on the topic:
- [Don't use auto unless you mean it](http://josephmansfield.uk/articles/dont-use-auto-unless-you-mean-it.html)
- [reddit](https://www.reddit.com/r/cpp/comments/50wdqj/any_example_codegithub_projects_utilising/)
- [CppCon Auto talk](https://www.youtube.com/watch?v=ZCGyvPDM0YY&list=PLHTh1InhhwT7J5jl4vAhO1WvGHUUFgUQH&index=21)
- [Another Opinion on AAA](https://probablydance.com/2014/10/04/another-opinion-on-almost-always-auto/)

**Comment by anonimal** [comment]
Thanks for the links @rakhimov
