### ISSUE TITLE
Use Boost.Log

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#33]
@majestrate expressed an interest in moving on this. I think its an essential idea but needs more research. See http://www.boost.org/doc/libs/1_59_0/libs/log/doc/html/log/rationale/fork_support.html

**Comment by anonimal** [comment]
In a normal world, this would be a minor enhancement. In Kovri's world, nothing is minor :sweat_smile:

**Comment by anonimal** [comment]
See #40

**Comment by anonimal** [comment]
Latest related commit: a94af0c047021740f00abd87d77ceb9afe0737d9
@majestrate, what else needs to be done in order to close this ticket?

**Comment by majestrate** [comment]
more testing of the code

**Comment by anonimal** [comment]
@majestrate should we write tests? And any thoughts on how we can swing this with #53?

**Comment by majestrate** [comment]
unit tests are a must

**Comment by anonimal** [comment]
Also, removal of deprecated log code.
