### ISSUE TITLE
AddressBook: discuss/implement multiple subscription files

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#337]
**By submitting this issue, I confirm the following:**
- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

_Place an X inside the bracket to confirm_
- [X] I confirm.

---

First, see #336. Then, consider [java i2p's naming spec](https://geti2p.net/en/docs/naming).

For this ticket, we should discuss if we're to have separate subscription files because we currently only use `hosts.txt`. Also, if we hand edit the file, it will be overridden upon next fetch from a _any_ publisher.

With a little design work, we can easily implement other files that won't be overridden. There's also the question of whether we want to have separate files for separate publishers.

Referencing #305 and #296

**Comment by anonimal** [comment]
In today's meeting we discussed an interesting solution:

1. `hosts.txt` will continue to be a static file updated upstream and clobbered every 12 hours. Users *do not* edit this file
2. `uri.host()_filename.txt` will be a unique subscription from unique publisher; re-named accordingly with the hostname of publisher **and** filename replaced with the filename provided by publisher (in case publisher publishes various subscriptions)
3. `private_hosts.txt` will be private subscriptions: never clobbered, never shared

This doesn't address *where* we save inserted addresses that are saved from an address helper since they currently are simply inserted into `./addressbook` though we could simply throw them into `private_hosts.txt`.

Issues that arise from this design:

- We lack an effective de-duplication impl
  - multiple subscriptions containing the same address(s) will simply take up space
  - If I load only one subscription and it doesn't have an address that another subscription has, after using a jumpservice, why would I save said address to `private_hosts.txt` when it already exists in another subscription?

Temporary solution:

- Until a database (#385) is implemented, we can scan and load *all* subscriptions on startup (but shouldn't we then fetch *all* subscriptions before scanning?). Any visited addresses can then be appended to `private_hosts.txt`.

Really all of this seems messy so I think we should push hard for #385.

**Comment by anonimal** [comment]
Note: #453 means that, on Win32/64 (only), the currently packaged `downloads.getmonero.org` subscription can never have ETag checked nor be downloaded/updated. This is an upstream issue being discussed in https://github.com/cpp-netlib/cpp-netlib/issues/696. Until that issue is resolved, we may be able to work with a server-side patch if the issue ends up being cipher-related (or similar).

**Comment by coneiric** [comment]
> In today's meeting we discussed an interesting solution

I really like the ideas from 1. 2. and 3, and I've been thinking of ways to implement de-duplication for addresses. 

What do you think of: 
- loading all entries from `hosts.txt` and `private_hosts.txt` on startup
- checking local subscription files (`host.uri()-filename.txt`) exist for all publishers
  - loaded from `publishers.txt`
- store (append) unique subscription entries in `private_hosts.txt`
  - entry not already loaded from `hosts.txt` or `private_hosts.txt`
- writing blank `host.uri()-filename.txt` to disk to signal the subscription has been processed
  - could also write a single line with timestamp to compare with `SubscriberUpdateTimer`
  - saves space for multiple subscriptions

Then if we wanted to mirror Java I2P's republish feature, the user could opt to save full subscription files in a separate folder.

Unique entries from republished subscriptions would still be appended to `private_hosts.txt`, but republished subscriptions wouldn't be processed on startup.

**Comment by anonimal** [comment]
>loading all entries from hosts.txt and private_hosts.txt on startup

You'll have to watch for the following:

1. Filesize. A trivial DoS will be to load a large filesize in the gigabytes range into memory without adequate checks or processing. This is one of several reasons why we need a database. Otherwise, we can simply do more disk access with the text file instead of loading everything into memory.
2. Load hosts.txt first then scan for unique hosts in private_hosts.txt. There's no point in loading both files into memory if there are duplicates.

>store (append) unique subscription entries in private_hosts.txt 

Concatenate all non-host.txt subscriptions into private_hosts.txt? That defeats the purpose my point 2 in previous comment.

>writing blank host.uri()-filename.txt to disk to signal the subscription has been processed
>could also write a single line with timestamp to compare with SubscriberUpdateTimer

For signaling that a file's been written? This is wholly unnecessary if that's the case. I can comment further once I know what you are trying to accomplish.

>Unique entries from republished subscriptions would still be appended to private_hosts.txt, but republished subscriptions wouldn't be processed on startup.

What do you mean by "republished"? Startup will fetch the latest subscriptions from publishers anyway or else the subscriptions will grow stale. Again, appending to private_hosts.txt defeats the purpose of private_hosts. Private means don't touch unless user explicitly touches it or wants us to touch it (yes, we're still talking about files :rofl:).

**Comment by coneiric** [comment]
Here is my current design plan, after digesting your previous comment, and working on the code a bit:
- Create new class `AddressBook::MemoryBook`
  - has two internal `std::map`s: `m_Book` + `m_PublisherBook`
  - `std::map<std::string host, kovri::core::IdentHash> m_Book` 
  - `std::map<std::string publisher, std::vector<AddressBook::Entry> entries> m_PublisherBook`
  - helps with entry separation (useful for #385)
  - `m_Book` will contain entries from hosts.txt + private_hosts.txt
    - neither of these files will be overwritten by `AddressBook`
    - in-memory separation of hosts from these files is not a concern

Loading subscription into memory:
- Default subscriptions loaded first
- Publisher subscriptions loaded next
  - duplicates not loaded into memory
  - unique entries added to vector, then `m_PublisherBook[publisher] = entry_vector`
  - only unique addresses written back to `uri.host()_hosts.txt`, if at all
  - duplicates from other subs not loaded into memory
  - read up to 256 addresses at a time from subscription files
  - configure max-size for subscription file?
  - if subscriptions are freshly downloaded every router restart/timer period, do we even want to keep publisher subscriptions on-disk?
    - if not, we could just delete `uri.host()_hosts.txt` after processing
    - would also allow for only one internal `std::map`
- Private subscriptions loaded last
  - duplicates not read into memory
  - unique addresses loaded into `m_Book`
  - on-disk storage not affected by `AddressBook` (file only changed manually by user)

Please let me know of any corrections/improvements I should make.

**Comment by anonimal** [comment]
NOTICE: THIS ISSUE HAS BEEN MOVED TO GitLab. Please continue the discussion there. See https://github.com/monero-project/kovri/issues/1013 for details.
