### ISSUE TITLE
Segfault upon SIGINT

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#342]
**By submitting this issue, I confirm the following:**
- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

_Place an X inside the bracket to confirm_
- [X] I confirm.

---

Built against 7f8c04f059b47c1ad6042d821313563cf4e7080e
Simple backtrace [attached](https://github.com/monero-project/kovri/files/465634/kovri_SIGINT_segfault_2016.09.10.txt).

**Comment by anonimal** [comment]
Another [backtrace](https://github.com/monero-project/kovri/files/466019/kovri_SIGINT_segfault_2016.09.11.txt), this time quickly after startup.

**Comment by anonimal** [comment]
fe270c0 fixes segfault but *only* if client destination isn't actively used (e.g., start router, wait for integration but don't connect to IRC, ctrl-c, exits normally); otherwise, we have a garlic related segfault ([backtrace attached](https://github.com/monero-project/kovri/files/470586/kovri_342_garlic.txt)).

**Comment by moneromooo** [comment]
I have a differnet stack trace when ^C fairly early:

Core was generated by `./build/kovri'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000353b009830 in pthread_mutex_lock () from /lib64/libpthread.so.0
warning: File "/home/user/gcc-5.4.0/lib64/libstdc++.so.6.0.21-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
	add-auto-load-safe-path /home/user/gcc-5.4.0/lib64/libstdc++.so.6.0.21-gdb.py
line to your configuration file "/home/user/.gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/home/user/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"
Missing separate debuginfos, use: debuginfo-install glibc-2.20-8.fc21.x86_64 keyutils-libs-1.5.9-4.fc21.x86_64 krb5-libs-1.12.2-19.fc21.x86_64 libcom_err-1.42.12-4.fc21.x86_64 libicu-52.1-6.fc21.x86_64 libselinux-2.3-10.fc21.x86_64 openssl-libs-1.0.1k-12.fc21.x86_64 pcre-8.35-14.fc21.x86_64 zlib-1.2.8-7.fc21.x86_64
(gdb) bt
#0  0x000000353b009830 in pthread_mutex_lock () from /lib64/libpthread.so.0
#1  0x0000000000ed00c8 in boost::asio::detail::posix_mutex::lock (this=0x8)
    at /home/user/boost_1_61_install/include/boost/asio/detail/posix_mutex.hpp:52
#2  0x0000000000efdce2 in boost::asio::detail::scoped_lock<boost::asio::detail::posix_mutex>::scoped_lock (this=0x7f6869ffa340, 
    m=...) at /home/user/boost_1_61_install/include/boost/asio/detail/scoped_lock.hpp:46
#3  0x0000000000f0e41c in boost::asio::detail::service_registry::do_use_service (this=0x0, key=..., 
    factory=0xf24ac4 <boost::asio::detail::service_registry::create<boost::asio::deadline_timer_service<boost::posix_time::ptime, boost::asio::time_traits<boost::posix_time::ptime> > >(boost::asio::io_service&)>)
    at /home/user/boost_1_61_install/include/boost/asio/detail/impl/service_registry.ipp:108
#4  0x0000000000f22508 in boost::asio::detail::service_registry::use_service<boost::asio::deadline_timer_service<boost::posix_time::ptime, boost::asio::time_traits<boost::posix_time::ptime> > > (this=0x0)
    at /home/user/boost_1_61_install/include/boost/asio/detail/impl/service_registry.hpp:48
#5  0x0000000000f1e7ce in boost::asio::use_service<boost::asio::deadline_timer_service<boost::posix_time::ptime, boost::asio::time_traits<boost::posix_time::ptime> > > (ios=...) at /home/user/boost_1_61_install/include/boost/asio/impl/io_service.hpp:33
#6  0x0000000000f194ff in boost::asio::basic_io_object<boost::asio::deadline_timer_service<boost::posix_time::ptime, boost::asio::time_traits<boost::posix_time::ptime> >, false>::basic_io_object (this=0x7f6858015150, io_service=...)
    at /home/user/boost_1_61_install/include/boost/asio/basic_io_object.hpp:90
#7  0x0000000000f139a5 in boost::asio::basic_deadline_timer<boost::posix_time::ptime, boost::asio::time_traits<boost::posix_time::ptime>, boost::asio::deadline_timer_service<boost::posix_time::ptime, boost::asio::time_traits<boost::posix_time::ptime> > >::basic_deadline_timer (this=0x7f6858015150, io_service=...) at /home/user/boost_1_61_install/include/boost/asio/basic_deadline_timer.hpp:149
#8  0x0000000001132050 in i2p::transport::SSUSession::SSUSession (this=0x7f6858014f00, server=..., remote_endpoint=..., router=..., 
    peer_test=false) at /home/user/src/kovri/src/core/transport/ssu_session.cc:90
#9  0x0000000001130bc6 in __gnu_cxx::new_allocator<i2p::transport::SSUSession>::construct<i2p::transport::SSUSession, i2p::transport::SSUServer&, boost::asio::ip::basic_endpoint<boost::asio::ip::udp>&> (this=0x7f6869ffa5d7, __p=0x7f6858014f00)
    at /home/user/gcc-5.4.0/include/c++/5.4.0/ext/new_allocator.h:120
#10 0x00000000011303aa in std::allocator_traits<std::allocator<i2p::transport::SSUSession> >::construct<i2p::transport::SSUSession, i2p::transport::SSUServer&, boost::asio::ip::basic_endpoint<boost::asio::ip::udp>&> (__a=..., __p=0x7f6858014f00)
    at /home/user/gcc-5.4.0/include/c++/5.4.0/bits/alloc_traits.h:530
#11 0x000000000112f52c in std::_Sp_counted_ptr_inplace<i2p::transport::SSUSession, std::allocator<i2p::transport::SSUSession>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<i2p::transport::SSUServer&, boost::asio::ip::basic_endpoint<boost::asio::ip::udp>&> (
    this=0x7f6858014ef0, __a=...) at /home/user/gcc-5.4.0/include/c++/5.4.0/bits/shared_ptr_base.h:522
#12 0x000000000112e01c in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<i2p::transport::SSUSession, std::allocator<i2p::transport::SSUSession>, i2p::transport::SSUServer&, boost::asio::ip::basic_endpoint<boost::asio::ip::udp>&> (
    this=0x7f6869ffa7f8, __a=...) at /home/user/gcc-5.4.0/include/c++/5.4.0/bits/shared_ptr_base.h:617
#13 0x000000000112c0ab in std::__shared_ptr<i2p::transport::SSUSession, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<i2p::transport::SSUSession>, i2p::transport::SSUServer&, boost::asio::ip::basic_endpoint<boost::asio::ip::udp>&> (this=0x7f6869ffa7f0, 
---Type <return> to continue, or q <return> to quit---
    __tag=..., __a=...) at /home/user/gcc-5.4.0/include/c++/5.4.0/bits/shared_ptr_base.h:1097
#14 0x0000000001128de0 in std::shared_ptr<i2p::transport::SSUSession>::shared_ptr<std::allocator<i2p::transport::SSUSession>, i2p::transport::SSUServer&, boost::asio::ip::basic_endpoint<boost::asio::ip::udp>&> (this=0x7f6869ffa7f0, __tag=..., __a=...)
    at /home/user/gcc-5.4.0/include/c++/5.4.0/bits/shared_ptr.h:319
#15 0x00000000011256b9 in std::allocate_shared<i2p::transport::SSUSession, std::allocator<i2p::transport::SSUSession>, i2p::transport::SSUServer&, boost::asio::ip::basic_endpoint<boost::asio::ip::udp>&> (__a=...)
    at /home/user/gcc-5.4.0/include/c++/5.4.0/bits/shared_ptr.h:620
#16 0x0000000001121d74 in std::make_shared<i2p::transport::SSUSession, i2p::transport::SSUServer&, boost::asio::ip::basic_endpoint<boost::asio::ip::udp>&> () at /home/user/gcc-5.4.0/include/c++/5.4.0/bits/shared_ptr.h:636
#17 0x000000000111d835 in i2p::transport::SSUServer::HandleReceivedPackets (this=0x1d30790, packets=...)
    at /home/user/src/kovri/src/core/transport/ssu.cc:252
#18 0x000000000113130f in std::_Mem_fn_base<void (i2p::transport::SSUServer::*)(std::vector<i2p::transport::RawSSUPacket*, std::allocator<i2p::transport::RawSSUPacket*> >), true>::operator()<std::vector<i2p::transport::RawSSUPacket*, std::allocator<i2p::transport::RawSSUPacket*> >&, void> (this=0x7f6869ffaa90, __object=0x1d30790) at /home/user/gcc-5.4.0/include/c++/5.4.0/functional:600
#19 0x0000000001130a91 in std::_Bind<std::_Mem_fn<void (i2p::transport::SSUServer::*)(std::vector<i2p::transport::RawSSUPacket*, std::allocator<i2p::transport::RawSSUPacket*> >)> (i2p::transport::SSUServer*, std::vector<i2p::transport::RawSSUPacket*, std::allocator<i2p::transport::RawSSUPacket*> >)>::__call<void, , 0ul, 1ul>(std::tuple<>&&, std::_Index_tuple<0ul, 1ul>) (this=0x7f6869ffaa90, 
    __args=<unknown type in /home/user/src/kovri/build/kovri, CU 0x13cdc71, DIE 0x144c07b>)
    at /home/user/gcc-5.4.0/include/c++/5.4.0/functional:1074
#20 0x0000000001130222 in std::_Bind<std::_Mem_fn<void (i2p::transport::SSUServer::*)(std::vector<i2p::transport::RawSSUPacket*, std::allocator<i2p::transport::RawSSUPacket*> >)> (i2p::transport::SSUServer*, std::vector<i2p::transport::RawSSUPacket*, std::allocator<i2p::transport::RawSSUPacket*> >)>::operator()<, void>() (this=0x7f6869ffaa90)
    at /home/user/gcc-5.4.0/include/c++/5.4.0/functional:1133
#21 0x000000000112f342 in boost::asio::asio_handler_invoke<std::_Bind<std::_Mem_fn<void (i2p::transport::SSUServer::*)(std::vector<i2p::transport::RawSSUPacket*, std::allocator<i2p::transport::RawSSUPacket*> >)> (i2p::transport::SSUServer*, std::vector<i2p::transport::RawSSUPacket*, std::allocator<i2p::transport::RawSSUPacket*> >)> >(std::_Bind<std::_Mem_fn<void (i2p::transport::SSUServer::*)(std::vector<i2p::transport::RawSSUPacket*, std::allocator<i2p::transport::RawSSUPacket*> >)> (i2p::transport::SSUServer*, std::vector<i2p::transport::RawSSUPacket*, std::allocator<i2p::transport::RawSSUPacket*> >)>&, ...) (function=...)
    at /home/user/boost_1_61_install/include/boost/asio/handler_invoke_hook.hpp:69
#22 0x000000000112df3b in boost_asio_handler_invoke_helpers::invoke<std::_Bind<std::_Mem_fn<void (i2p::transport::SSUServer::*)(std::vector<i2p::transport::RawSSUPacket*, std::allocator<i2p::transport::RawSSUPacket*> >)> (i2p::transport::SSUServer*, std::vector<i2p::transport::RawSSUPacket*, std::allocator<i2p::transport::RawSSUPacket*> >)>, std::_Bind<std::_Mem_fn<void (i2p::transport::SSUServer::*)(std::vector<i2p::transport::RawSSUPacket*, std::allocator<i2p::transport::RawSSUPacket*> >)> (i2p::transport::SSUServer*, std::vector<i2p::transport::RawSSUPacket*, std::allocator<i2p::transport::RawSSUPacket*> >)> >(std::_Bind<std::_Mem_fn<void (i2p::transport::SSUServer::*)(std::vector<i2p::transport::RawSSUPacket*, std::allocator<i2p::transport::RawSSUPacket*> >)> (i2p::transport::SSUServer*, std::vector<i2p::transport::RawSSUPacket*, std::allocator<i2p::transport::RawSSUPacket*> >)>&, std::_Bind<std::_Mem_fn<void (i2p::trans---Type <return> to continue, or q <return> to quit---
port::SSUServer::*)(std::vector<i2p::transport::RawSSUPacket*, std::allocator<i2p::transport::RawSSUPacket*> >)> (i2p::transport::SSUServer*, std::vector<i2p::transport::RawSSUPacket*, std::allocator<i2p::transport::RawSSUPacket*> >)>&) (function=..., context=...)
    at /home/user/boost_1_61_install/include/boost/asio/detail/handler_invoke_helpers.hpp:37
#23 0x000000000112bfa1 in boost::asio::detail::completion_handler<std::_Bind<std::_Mem_fn<void (i2p::transport::SSUServer::*)(std::vector<i2p::transport::RawSSUPacket*, std::allocator<i2p::transport::RawSSUPacket*> >)> (i2p::transport::SSUServer*, std::vector<i2p::transport::RawSSUPacket*, std::allocator<i2p::transport::RawSSUPacket*> >)> >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) (owner=0x1d1cf90, base=0x7f68580178a0)
    at /home/user/boost_1_61_install/include/boost/asio/detail/completion_handler.hpp:68
#24 0x0000000000f0e5bc in boost::asio::detail::task_io_service_operation::complete (this=0x7f68580178a0, owner=..., ec=..., 
    bytes_transferred=0) at /home/user/boost_1_61_install/include/boost/asio/detail/task_io_service_operation.hpp:38
#25 0x0000000000f0ff82 in boost::asio::detail::task_io_service::do_run_one (this=0x1d1cf90, lock=..., this_thread=..., ec=...)
    at /home/user/boost_1_61_install/include/boost/asio/detail/impl/task_io_service.ipp:372
#26 0x0000000000f0fbf2 in boost::asio::detail::task_io_service::run (this=0x1d1cf90, ec=...)
    at /home/user/boost_1_61_install/include/boost/asio/detail/impl/task_io_service.ipp:149
#27 0x0000000000f1009f in boost::asio::io_service::run (this=0x15d1ad0 <i2p::transport::transports+16>)
    at /home/user/boost_1_61_install/include/boost/asio/impl/io_service.ipp:59
#28 0x000000000106ccdd in i2p::transport::Transports::Run (this=0x15d1ac0 <i2p::transport::transports>)
    at /home/user/src/kovri/src/core/transport/transports.cc:229
#29 0x000000000107fc5b in std::_Mem_fn_base<void (i2p::transport::Transports::*)(), true>::operator()<, void>(i2p::transport::Transports*) const (this=0x1d4c168, __object=0x15d1ac0 <i2p::transport::transports>) at /home/user/gcc-5.4.0/include/c++/5.4.0/functional:600
#30 0x000000000107fb76 in std::_Bind<std::_Mem_fn<void (i2p::transport::Transports::*)()> (i2p::transport::Transports*)>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) (this=0x1d4c168, 
    __args=<unknown type in /home/user/src/kovri/build/kovri, CU 0xe5e371, DIE 0xeff4f2>)
    at /home/user/gcc-5.4.0/include/c++/5.4.0/functional:1074
#31 0x000000000107fabc in std::_Bind<std::_Mem_fn<void (i2p::transport::Transports::*)()> (i2p::transport::Transports*)>::operator()<, void>() (this=0x1d4c168) at /home/user/gcc-5.4.0/include/c++/5.4.0/functional:1133
#32 0x000000000107fa32 in std::_Bind_simple<std::_Bind<std::_Mem_fn<void (i2p::transport::Transports::*)()> (i2p::transport::Transports*)> ()>::_M_invoke<>(std::_Index_tuple<>) (this=0x1d4c168) at /home/user/gcc-5.4.0/include/c++/5.4.0/functional:1531
#33 0x000000000107f90f in std::_Bind_simple<std::_Bind<std::_Mem_fn<void (i2p::transport::Transports::*)()> (i2p::transport::Transports*)> ()>::operator()() (this=0x1d4c168) at /home/user/gcc-5.4.0/include/c++/5.4.0/functional:1520
#34 0x000000000107f80e in std::thread::_Impl<std::_Bind_simple<std::_Bind<std::_Mem_fn<void (i2p::transport::Transports::*)()> (i2p::transport::Transports*)> ()> >::_M_run() (this=0x1d4c150) at /home/user/gcc-5.4.0/include/c++/5.4.0/thread:115
#35 0x00007f6871d2d820 in std::execute_native_thread_routine (__p=<optimized out>)
    at ../../../../../libstdc++-v3/src/c++11/thread.cc:84
#36 0x000000353b00752a in start_thread () from /lib64/libpthread.so.0
#37 0x000000353ad0022d in clone () from /lib64/libc.so.6

Log:
https://paste.fedoraproject.org/441911/35938147/

**Comment by guzzijones** [comment]
wow. nice work anonimal.  how you found this i have no idea. i hope to be as awesome as you some day.

**Comment by anonimal** [comment]
lol, @guzzijones you're too much 😄 I hope to be as awesome as *you* some day 😉

The backtrace said it all. I could've spent time with a custom deleter (or refactored elsewhere) but, since there is no *current* (and I mean current) reason to enforce pointer ownership in this *particular* area, I thought that a raw pointer would suffice for now (IMHO).
