### ISSUE TITLE
Crypto: upgrade to supercop to latest release

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#345]
**By submitting this issue, I confirm the following:**
- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

_Place an X inside the bracket to confirm_
- [X] I confirm.

---

https://bench.cr.yp.to/supercop.html

**Comment by EinMByte** [comment]
Note that our EdDSA implementation is not an exact copy of the supercop implementation.

**Comment by anonimal** [comment]
Possibly the two easiest options for now:

1. Add https://github.com/anonimal/supercop-ed25519-ref10 as a submodule, make changes locally and resolve any merge conflicts
2. Create branch `kovri` in https://github.com/anonimal/supercop-ed25519-ref10, add as a submodule, push directly to branch `kovri` our local (kovri-specific) changes alongside every SUPERCOP update

Point 1 seems most reasonable of the two.

**Comment by anonimal** [comment]
Referencing #485.

**Comment by anonimal** [comment]
JFTR: upgrading will bring API changes that break our current polymorphic signer/verifier implementation. Will discuss more on IRC.

**Comment by anonimal** [comment]
Note: this issue will no longer be relevant once https://github.com/monero-project/kovri/issues/485#issuecomment-358588236 is resolved.
