### ISSUE TITLE
Windows: MinGW64/MSYS2 build errors

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#36]
Even with dependencies installed, doesn't build. ~~Errors similar to <a href="https://stackoverflow.com/questions/4101456/running-cmake-on-windows" target="_blank">here</a>. Passing the appropriate `-DCMAKE_C_COMPILER=` and `-DCMAKE_CXX_COMPILER=` has no effect.~~

This could be a cmake issue or an improperly setup mingw64 (specific for Kovri) because we haven't provided the correct installation criteria or mingw-friendly dependencies.

**Comment by anonimal** [comment]
Building ```cd ~/kovri/build && cmake -G 'MSYS Makefiles' ../ && make``` against ```mingw-w64-x86_64-crypto++ 5.6.3-2``` fails when linking core.  Client also fails to compile with ```std::fstream```.

Details and paste [here](https://paste.fedoraproject.org/388443/46783336/raw/).

**Comment by anonimal** [comment]
Our build process has changed since previous post. I'll post newer results when I get them.

**Comment by anonimal** [comment]
Referencing https://github.com/weidai11/cryptopp/issues/237

**Comment by anonimal** [comment]
https://github.com/weidai11/cryptopp/issues/237 has been fixed.

Our TODO's:
- Refactor boost's ```c_str()``` to ```string()``` for ```ifstream``` in ```src/client/AddressBook.cpp```
- Fill in the missing code for window's filesystem/service (```MAX_PATH```, etc.)
- Resolve any other compile-time issues (after these, there shouldn't be any for mingw)
- Resolve any linkage errors that should arise

**Comment by anonimal** [comment]
#288 resolves compilation errors. Now we simply have to deal with linkage.

@luigi1111 feel free to paste the linkage errors that come up with regular ```make``` or ```make optimized-hardening``` or ```make all-options```, or I can paste later this week (or sometime next week).  If you have any fixes that would be great too.

**Comment by luigi1111** [comment]
`make`

`[100%] Linking CXX executable ../../kovri.exe
CMakeFiles/kovri-app.dir/objects.a(Daemon.cpp.obj): In function `boost::asio::detail::winsock_init_base::startup(boost::asio::detail::winsock_init_base::data&, unsigned char, unsigned char)':
C:/msys64/mingw64/include/boost/asio/detail/impl/winsock_init.ipp:39: undefined reference to `__imp_WSAStartup'
CMakeFiles/kovri-app.dir/objects.a(Daemon.cpp.obj): In function `boost::asio::detail::winsock_init_base::cleanup(boost::asio::detail::winsock_init_base::data&)':
C:/msys64/mingw64/include/boost/asio/detail/impl/winsock_init.ipp:56: undefined reference to `__imp_WSACleanup'
CMakeFiles/kovri-app.dir/objects.a(Daemon.cpp.obj): In function `boost::asio::detail::socket_ops::clear_last_error()':
C:/msys64/mingw64/include/boost/asio/detail/impl/socket_ops.ipp:69: undefined reference to `__imp_WSASetLastError'
CMakeFiles/kovri-app.dir/objects.a(Daemon.cpp.obj): In function `boost::asio::detail::socket_ops::inet_pton(int, char const*, void*, unsigned long*, boost::system::error_code&)':
C:/msys64/mingw64/include/boost/asio/detail/impl/socket_ops.ipp:2201: undefined reference to `__imp_WSAStringToAddressA'
CMakeFiles/kovri-app.dir/objects.a(Daemon.cpp.obj): In function `int boost::asio::detail::socket_ops::error_wrapper<int>(int, boost::system::error_code&)':
C:/msys64/mingw64/include/boost/asio/detail/impl/socket_ops.ipp:82: undefined reference to `__imp_WSAGetLastError'
../../libkovri-client.a(I2PControlServer.cpp.obj): In function `boost::asio::detail::socket_ops::complete_iocp_accept(unsigned long long, void*, unsigned long, sockaddr*, unsigned long long*, unsigned long long, boost::system::error_code&)':
C:/msys64/mingw64/include/boost/asio/detail/impl/socket_ops.ipp:199: undefined reference to `GetAcceptExSockaddrs'
../../libkovri-client.a(I2PControlServer.cpp.obj): In function `boost::asio::detail::socket_ops::close(unsigned long long, unsigned char&, bool, boost::system::error_code&)':
C:/msys64/mingw64/include/boost/asio/detail/impl/socket_ops.ipp:317: undefined reference to `__imp_closesocket'
C:/msys64/mingw64/include/boost/asio/detail/impl/socket_ops.ipp:334: undefined reference to `__imp_ioctlsocket'
C:/msys64/mingw64/include/boost/asio/detail/impl/socket_ops.ipp:349: undefined reference to `__imp_closesocket'
../../libkovri-client.a(I2PControlServer.cpp.obj): In function `boost::asio::detail::socket_ops::listen(unsigned long long, int, boost::system::error_code&)':
C:/msys64/mingw64/include/boost/asio/detail/impl/socket_ops.ipp:694: undefined reference to `__imp_listen'
../../libkovri-client.a(I2PControlServer.cpp.obj): In function `boost::asio::detail::socket_ops::send(unsigned long long, _WSABUF const*, unsigned long long, int, boost::system::error_code&)':
C:/msys64/mingw64/include/boost/asio/detail/impl/socket_ops.ipp:1153: undefined reference to `__imp_WSASend'
../../libkovri-client.a(I2PControlServer.cpp.obj): In function `boost::asio::detail::socket_ops::socket(int, int, int, boost::system::error_code&)':
C:/msys64/mingw64/include/boost/asio/detail/impl/socket_ops.ipp:1381: undefined reference to `__imp_WSASocketW'
C:/msys64/mingw64/include/boost/asio/detail/impl/socket_ops.ipp:1393: undefined reference to `__imp_setsockopt'
../../libkovri-client.a(I2PControlServer.cpp.obj): In function `boost::asio::detail::socket_ops::inet_ntop(int, void const*, char*, unsigned long long, unsigned long, boost::system::error_code&)':
C:/msys64/mingw64/include/boost/asio/detail/impl/socket_ops.ipp:1993: undefined reference to `__imp_WSAAddressToStringA'
../../libkovri-client.a(I2PControlServer.cpp.obj): In function `boost::asio::detail::socket_ops::network_to_host_long(unsigned long)':
C:/msys64/mingw64/include/boost/asio/detail/impl/socket_ops.ipp:3388: undefined reference to `__imp_ntohl'
../../libkovri-client.a(I2PControlServer.cpp.obj): In function `boost::asio::detail::socket_ops::host_to_network_long(unsigned long)':
C:/msys64/mingw64/include/boost/asio/detail/impl/socket_ops.ipp:3403: undefined reference to `__imp_htonl'
../../libkovri-client.a(I2PControlServer.cpp.obj): In function `boost::asio::detail::socket_ops::network_to_host_short(unsigned short)':
C:/msys64/mingw64/include/boost/asio/detail/impl/socket_ops.ipp:3415: undefined reference to `__imp_ntohs'
../../libkovri-client.a(I2PControlServer.cpp.obj): In function `boost::asio::detail::socket_ops::host_to_network_short(unsigned short)':
C:/msys64/mingw64/include/boost/asio/detail/impl/socket_ops.ipp:3428: undefined reference to `__imp_htons'
../../libkovri-client.a(I2PControlServer.cpp.obj): In function `boost::asio::detail::win_iocp_socket_service_base::start_send_op(boost::asio::detail::win_iocp_socket_service_base::base_implementation_type&, _WSABUF*, unsigned long long, int, bool, boost::asio::detail::win_iocp_operation*)':
C:/msys64/mingw64/include/boost/asio/detail/impl/win_iocp_socket_service_base.ipp:357: undefined reference to `__imp_WSASend'
C:/msys64/mingw64/include/boost/asio/detail/impl/win_iocp_socket_service_base.ipp:358: undefined reference to `__imp_WSAGetLastError'
../../libkovri-client.a(I2PControlServer.cpp.obj): In function `boost::asio::detail::win_iocp_socket_service_base::start_receive_op(boost::asio::detail::win_iocp_socket_service_base::base_implementation_type&, _WSABUF*, unsigned long long, int, bool, boost::asio::detail::win_iocp_operation*)':
C:/msys64/mingw64/include/boost/asio/detail/impl/win_iocp_socket_service_base.ipp:413: undefined reference to `__imp_WSARecv'
C:/msys64/mingw64/include/boost/asio/detail/impl/win_iocp_socket_service_base.ipp:414: undefined reference to `__imp_WSAGetLastError'
../../libkovri-client.a(I2PControlServer.cpp.obj): In function `boost::asio::detail::win_iocp_socket_service_base::start_accept_op(boost::asio::detail::win_iocp_socket_service_base::base_implementation_type&, bool, boost::asio::detail::socket_holder&, int, int, int, void*, unsigned long, boost::asio::detail::win_iocp_operation*)':
C:/msys64/mingw64/include/boost/asio/detail/impl/win_iocp_socket_service_base.ipp:495: undefined reference to `AcceptEx'
C:/msys64/mingw64/include/boost/asio/detail/impl/win_iocp_socket_service_base.ipp:496: undefined reference to `__imp_WSAGetLastError'
../../libkovri-client.a(I2PControlServer.cpp.obj): In function `boost::asio::detail::win_iocp_socket_service_base::restart_accept_op(unsigned long long, boost::asio::detail::socket_holder&, int, int, int, void*, unsigned long, boost::asio::detail::win_iocp_operation*)':
C:/msys64/mingw64/include/boost/asio/detail/impl/win_iocp_socket_service_base.ipp:520: undefined reference to `AcceptEx'
C:/msys64/mingw64/include/boost/asio/detail/impl/win_iocp_socket_service_base.ipp:521: undefined reference to `__imp_WSAGetLastError'
../../libkovri-client.a(I2PControlServer.cpp.obj): In function `unsigned long long boost::asio::detail::socket_ops::error_wrapper<unsigned long long>(unsigned long long, boost::system::error_code&)':
C:/msys64/mingw64/include/boost/asio/detail/impl/socket_ops.ipp:82: undefined reference to `__imp_WSAGetLastError'
../../libkovri-client.a(I2PControlServer.cpp.obj): In function `int boost::asio::detail::socket_ops::call_bind<int>(int boost::asio::detail::socket_ops::msghdr::*, unsigned long long, sockaddr const*, unsigned long long)':
C:/msys64/mingw64/include/boost/asio/detail/impl/socket_ops.ipp:276: undefined reference to `__imp_bind'
../../libkovri-client.a(I2PControlServer.cpp.obj): In function `int boost::asio::detail::socket_ops::call_setsockopt<int>(int boost::asio::detail::socket_ops::msghdr::*, unsigned long long, int, int, void const*, unsigned long long)':
C:/msys64/mingw64/include/boost/asio/detail/impl/socket_ops.ipp:1428: undefined reference to `__imp_setsockopt'
../../libkovri-client.a(I2PControlServer.cpp.obj): In function `int boost::asio::detail::socket_ops::call_getsockopt<int>(int boost::asio::detail::socket_ops::msghdr::*, unsigned long long, int, int, void*, unsigned long long*)':
C:/msys64/mingw64/include/boost/asio/detail/impl/socket_ops.ipp:1514: undefined reference to `__imp_getsockopt'
../../libkovri-client.a(I2PControlServer.cpp.obj): In function `int boost::asio::detail::socket_ops::call_getpeername<int>(int boost::asio::detail::socket_ops::msghdr::*, unsigned long long, sockaddr*, unsigned long long*)':
C:/msys64/mingw64/include/boost/asio/detail/impl/socket_ops.ipp:1623: undefined reference to `__imp_getpeername'
../../libkovri-client.a(I2PTunnel.cpp.obj): In function `boost::asio::detail::win_fd_set_adapter::is_set(unsigned long long) const':
C:/msys64/mingw64/include/boost/asio/detail/win_fd_set_adapter.hpp:83: undefined reference to `__WSAFDIsSet'
../../libkovri-client.a(I2PTunnel.cpp.obj): In function `boost::asio::detail::socket_ops::set_internal_non_blocking(unsigned long long, unsigned char&, bool, boost::system::error_code&)':
C:/msys64/mingw64/include/boost/asio/detail/impl/socket_ops.ipp:426: undefined reference to `__imp_ioctlsocket'
../../libkovri-client.a(I2PTunnel.cpp.obj): In function `boost::asio::detail::socket_ops::non_blocking_connect(unsigned long long, boost::system::error_code&)':
C:/msys64/mingw64/include/boost/asio/detail/impl/socket_ops.ipp:576: undefined reference to `__imp_select'
../../libkovri-client.a(I2PTunnel.cpp.obj): In function `boost::asio::detail::socket_ops::recv(unsigned long long, _WSABUF*, unsigned long long, int, boost::system::error_code&)':
C:/msys64/mingw64/include/boost/asio/detail/impl/socket_ops.ipp:770: undefined reference to `__imp_WSARecv'
../../libkovri-client.a(I2PTunnel.cpp.obj): In function `boost::asio::detail::socket_ops::ioctl(unsigned long long, unsigned char&, int, unsigned long*, boost::system::error_code&)':
C:/msys64/mingw64/include/boost/asio/detail/impl/socket_ops.ipp:1711: undefined reference to `__imp_ioctlsocket'
../../libkovri-client.a(I2PTunnel.cpp.obj): In function `boost::asio::detail::socket_ops::select(int, fd_set*, fd_set*, fd_set*, timeval*, boost::system::error_code&)':
C:/msys64/mingw64/include/boost/asio/detail/impl/socket_ops.ipp:1780: undefined reference to `__imp_select'
../../libkovri-client.a(I2PTunnel.cpp.obj): In function `boost::asio::detail::socket_ops::translate_addrinfo_error(int)':
C:/msys64/mingw64/include/boost/asio/detail/impl/socket_ops.ipp:3201: undefined reference to `__imp_WSAGetLastError'
../../libkovri-client.a(I2PTunnel.cpp.obj): In function `boost::asio::detail::socket_ops::getaddrinfo(char const*, char const*, addrinfo const&, addrinfo**, boost::system::error_code&)':
C:/msys64/mingw64/include/boost/asio/detail/impl/socket_ops.ipp:3219: undefined reference to `__imp_getaddrinfo'
../../libkovri-client.a(I2PTunnel.cpp.obj): In function `boost::asio::detail::socket_ops::freeaddrinfo(addrinfo*)':
C:/msys64/mingw64/include/boost/asio/detail/impl/socket_ops.ipp:3262: undefined reference to `__imp_freeaddrinfo'
../../libkovri-client.a(I2PTunnel.cpp.obj): In function `boost::asio::detail::win_iocp_socket_service_base::start_connect_op(boost::asio::detail::win_iocp_socket_service_base::base_implementation_type&, int, int, sockaddr const*, unsigned long long, boost::asio::detail::win_iocp_socket_connect_op_base*)':
C:/msys64/mingw64/include/boost/asio/detail/impl/win_iocp_socket_service_base.ipp:584: undefined reference to `__imp_WSAGetLastError'
../../libkovri-client.a(I2PTunnel.cpp.obj): In function `boost::asio::detail::win_iocp_socket_service_base::get_connect_ex(boost::asio::detail::win_iocp_socket_service_base::base_implementation_type&, int)':
C:/msys64/mingw64/include/boost/asio/detail/impl/win_iocp_socket_service_base.ipp:690: undefined reference to `__imp_WSAIoctl'
../../libkovri-client.a(I2PTunnel.cpp.obj): In function `unsigned long long boost::asio::detail::socket_ops::call_accept<int>(int boost::asio::detail::socket_ops::msghdr::*, unsigned long long, sockaddr*, unsigned long long*)':
C:/msys64/mingw64/include/boost/asio/detail/impl/socket_ops.ipp:96: undefined reference to `__imp_accept'
../../libkovri-client.a(I2PTunnel.cpp.obj): In function `int boost::asio::detail::socket_ops::call_connect<int>(int boost::asio::detail::socket_ops::msghdr::*, unsigned long long, sockaddr const*, unsigned long long)':
C:/msys64/mingw64/include/boost/asio/detail/impl/socket_ops.ipp:472: undefined reference to `__imp_connect'
../../libkovri-client.a(I2PTunnel.cpp.obj): In function `int boost::asio::detail::socket_ops::call_getsockname<int>(int boost::asio::detail::socket_ops::msghdr::*, unsigned long long, sockaddr*, unsigned long long*)':
C:/msys64/mingw64/include/boost/asio/detail/impl/socket_ops.ipp:1678: undefined reference to `__imp_getsockname'
../../libkovri-core.a(HTTP.cpp.obj): In function `boost::asio::detail::socket_ops::poll_read(unsigned long long, unsigned char, boost::system::error_code&)':
C:/msys64/mingw64/include/boost/asio/detail/impl/socket_ops.ipp:1807: undefined reference to `__imp_select'
../../libkovri-core.a(HTTP.cpp.obj): In function `boost::asio::detail::socket_ops::poll_write(unsigned long long, unsigned char, boost::system::error_code&)':
C:/msys64/mingw64/include/boost/asio/detail/impl/socket_ops.ipp:1848: undefined reference to `__imp_select'
../../libkovri-core.a(HTTP.cpp.obj): In function `boost::asio::detail::socket_ops::poll_connect(unsigned long long, boost::system::error_code&)':
C:/msys64/mingw64/include/boost/asio/detail/impl/socket_ops.ipp:1888: undefined reference to `__imp_select'
../../libkovri-core.a(MTU.cpp.obj): In function `inet_pton(int, char const*, void*)':
C:/msys64/home/dist/kovri/src/core/util/MTU.cpp:68: undefined reference to `__imp_WSAStringToAddressA'
../../libkovri-core.a(MTU.cpp.obj): In function `i2p::util::mtu::GetMTUWindowsIpv4(sockaddr_in, int)':
C:/msys64/home/dist/kovri/src/core/util/MTU.cpp:151: undefined reference to `GetAdaptersAddresses'
C:/msys64/home/dist/kovri/src/core/util/MTU.cpp:165: undefined reference to `GetAdaptersAddresses'
../../libkovri-core.a(MTU.cpp.obj): In function `i2p::util::mtu::GetMTUWindowsIpv6(sockaddr_in6, int)':
C:/msys64/home/dist/kovri/src/core/util/MTU.cpp:211: undefined reference to `GetAdaptersAddresses'
C:/msys64/home/dist/kovri/src/core/util/MTU.cpp:225: undefined reference to `GetAdaptersAddresses'
../../libkovri-core.a(NTCPSession.cpp.obj): In function `boost::asio::detail::socket_ops::available(unsigned long long, boost::system::error_code&)':
C:/msys64/mingw64/include/boost/asio/detail/impl/socket_ops.ipp:671: undefined reference to `__imp_ioctlsocket'
../../libkovri-core.a(SSU.cpp.obj): In function `boost::asio::detail::socket_ops::recvfrom(unsigned long long, _WSABUF*, unsigned long long, int, sockaddr*, unsigned long long*, boost::system::error_code&)':
C:/msys64/mingw64/include/boost/asio/detail/impl/socket_ops.ipp:917: undefined reference to `__imp_WSARecvFrom'
../../libkovri-core.a(SSU.cpp.obj): In function `boost::asio::detail::socket_ops::sendto(unsigned long long, _WSABUF const*, unsigned long long, int, sockaddr const*, unsigned long long, boost::system::error_code&)':
C:/msys64/mingw64/include/boost/asio/detail/impl/socket_ops.ipp:1279: undefined reference to `__imp_WSASendTo'
../../libkovri-core.a(SSU.cpp.obj): In function `boost::asio::detail::win_iocp_socket_service_base::start_receive_from_op(boost::asio::detail::win_iocp_socket_service_base::base_implementation_type&, _WSABUF*, unsigned long long, sockaddr*, int, int*, boost::asio::detail::win_iocp_operation*)':
C:/msys64/mingw64/include/boost/asio/detail/impl/win_iocp_socket_service_base.ipp:462: undefined reference to `__imp_WSARecvFrom'
C:/msys64/mingw64/include/boost/asio/detail/impl/win_iocp_socket_service_base.ipp:463: undefined reference to `__imp_WSAGetLastError'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [src/app/CMakeFiles/kovri-app.dir/build.make:245: kovri.exe] Error 1
make[1]: *** [CMakeFiles/Makefile2:114: src/app/CMakeFiles/kovri-app.dir/all] Error 2
make: *** [Makefile:128: all] Error 2
`

**Comment by anonimal** [comment]
New build log (IIRC same errors that were in the now expired fpaste): https://build.getmonero.org/builders/kovri-tests-win64/builds/1/steps/compile/logs/stdio
