### ISSUE TITLE
Remove CodeDocs

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#360]
**By submitting this issue, I confirm the following:**

- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

*Place an X inside the bracket to confirm*
- [X] I confirm.

---

40+ minutes ago, #358 was merged and https://codedocs.xyz/monero-project/kovri/ looks as it did before (see [attached](https://cloud.githubusercontent.com/assets/12156341/18557348/13e8e976-7b5e-11e6-9aad-ce65f1c6aea6.png)).

I don't know if the service/site is maintained and/or buggy, but I don't think the service has proven itself useful enough for us to warrant debugging.

We have a working `make doxygen` option which is maintained. As such, I think we should remove CodeDocs from README and repository (unless someone wants to try to fix this issue).

**Comment by EinMByte** [comment]
Agreed, codedocs looks empty to me.

**Comment by anonimal** [comment]
@fluffypony can you also please remove the application from repo settings (if its there)?

**Comment by anonimal** [comment]
Reopened until repo setting is resolved.

**Comment by fluffypony** [comment]
Ok I've disabled it - their interface was a bit weird, and it made me re-auth the Github OAuth tag, so if it still persists let me know.

**Comment by anonimal** [comment]
Ok, thanks @fluffypony
