### ISSUE TITLE
Log: kovri_%1N.log produces > 1N

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#375]
**By submitting this issue, I confirm the following:**
- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

_Place an X inside the bracket to confirm_
- [X] I confirm.

---

Review `boost::log::keywords::file_name` for log rotation. We currently rotate every 10 MiB against textual template `%1N`.

**Comment by anonimal** [comment]
```
&anonimal | Re: logging,
&anonimal | I'm thinking of the following DEFAULT solutions for now: 
&anonimal | 1. Default logging will be 'warn error' only. Still customizable with --log-levels
&anonimal | 2. Rotation at midnight, regardless of size (should be very small though)
&anonimal | 3. Log dir cleaned up every 7 days
&anonimal | This will allow us or users to do at least *some* statistics over a week instead of clobbering a single log file at a specific file size. 
&anonimal | With those parameters in place, even with all log levels set, total files size (when combined) would only every reach ~2-3 GiB. With warn/error only, I'm estimating much lower; in the range of MiB.
```

**Comment by EinMByte** [comment]
@anonimal Sounds like a good plan.

**Comment by anonimal** [comment]
This tickets points out another related issue of the need for a logging standard, e.g.; *what to log* and *how to classify content*. Currently there are too many 'info' messages should be 'debug' and, in all, there's not enough useful 'info' messages. This negatively effects user experience, IMHO.

I'd rather not disable 'info' because there is actually useful info there so, what I think I (or someone) should done is a quick moving of 'info' to 'debug' for the most obvious spamming messages (lots in transports, etc.) while I (or they) work on this ticket.

**Comment by EinMByte** [comment]
Eventually we need to move to scoped logging (per-class or per-topic such as NTCP, SSU, netDb...) IMHO.

**Comment by anonimal** [comment]
Referencing #223

**Comment by anonimal** [comment]
> &anonimal | 3. Log dir cleaned up every 7 days

Since we'll start using `rotation_at_time_point`,  when setting a file collector for the sink, this *could* be easily implemented with `boost::log::keywords::max_files` **but** `max_files` was only introduced in boost 1.61 and, since I regularly develop on Arch, I didn't realize this until now after testing on Ubuntu (which still packages 1.58).

Implementing our own log rotation, even when hooking into `set_close_handler`, would be a bit odd as it would entail implementing a lot of other code to test date of files in log dir and to subsequently remove appropriate ones - all while not interfering with current log file in use. It's not impossible, and there's probably a better way to do something like that but, in all, I don't think it's worth the effort right now when considering every other factor as mentioned in the above comments - and log rotation *can* be incumbent upon the user. Also note that any attempt to alter file size / rotate by file size would interfere with daily logging, but solutions are possible.

I think, for now, in addition to what was prescribed in https://github.com/monero-project/kovri/issues/375#issuecomment-250908675 (and to reiterate/confirm):
- change the template to something like `kovri_%Y-%m-%d.log`
- rotate to a new file every day at midnight
- set default log levels to `info warn error` after I do a global review of appropriate log levels (as mentioned above)

There are many ways to skin this 🐈. I think the penultimate goals for this issue will be satisfactory enough until we do a logger overhaul but, in the meantime, ideas are welcome.
