### ISSUE TITLE
I2PControlService: handle request exception: <unspecified file>(1): expected value

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#377]
**By submitting this issue, I confirm the following:**
- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

_Place an X inside the bracket to confirm_
- [X] I confirm.
---

April 20th, 24087070c48347d93ce0f897e3ea194c235f7afd, was the last time I looked at I2PControl when I rewrote the token generation impl. Because my tests at the time were outside of kovri, I confirmed that the refactor worked - though I never tried to use I2PControl until now.

When using [i2p.itoopie](https://github.com/i2p/i2p.itoopie), connecting will produce the following `std::exception` when handling `ReadRequest()`:

```
NFO   I2PControlService: new I2PControl request from 127.0.0.1:53018
ERR   I2PControlService: handle request exception: <unspecified file>(1): expected value
```

This error is unrelated to the aforementioned refactor. I've never assumed that I2PControl ever worked on kovri - so I won't start now :wink:

**Comment by EinMByte** [comment]
I2PControl works fine when using [qtoopie](https://github.com/EinMByte/qtoopie) or the test scripts.
The exception seems to be due to `boost::property_tree`, so my guess is that the implementation is somehow unable to handle the JSON sent by I2PControl. In any case, this needs more research.

**Comment by anonimal** [comment]
Oops, I was using proxychains with qtoopie. Even with localnet enabled, I2PControl was not responding (so I assumed it was kovri and not qtoopie). Using qtoopie without proxychains produces results.

**Comment by majestrate** [comment]
I believe this occurs when parsing a request buffer that has 0 bytes length.

This occurs in i2pd as well, possibly for similar reasons. The major deviation is that i2pd forces ssl.

**Comment by anonimal** [comment]
I cannot reproduce this issue anymore.

The new error that's thrown `I2PControlService: handle request exception: <unspecified file>(1): expected object or array` is easily remedied by [not using hardcoded https in itoopie](https://github.com/i2p/i2p.itoopie/blob/master/src/net/i2p/itoopie/i2pcontrol/JSONRPC2Interface.java#L51) - even for localhost (as the handler is obviously expecting a different payload).

itoopie now connects after removing hardcoded https but is not functioning as expected though qtoopie *continues* to function normally as expected.

itoopie issues are for itoopie and any new implementation issues on our end can be opened in a new ticket. As for https, we'll enable https for local sockets after more cpp-netlib refactoring and review.
