### ISSUE TITLE
Remove claim for Visual Studio support

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#38]
In <a href="https://github.com/monero-project/kovri/blob/master/doc/REQUIREMENTS.md" target="_blank">REQUIREMENTS</a> either remove/replace with something else or get our hands on VS >= 2013. At this point in time, I cannot verify that we build with VS; can anyone else?

**Comment by EinMByte** [comment]
I could try to fix this sometime in the future. I got it working before.
