### ISSUE TITLE
Travis CI: disable repo in travis-ci.org

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#394]
**By submitting this issue, I confirm the following:**

- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

*Place an X inside the bracket to confirm*
- [X] I confirm.

---

We're no longer using Travis CI. If its not disabled in travis-ci.org, we'll continue to get errors in https://travis-ci.org/monero-project/kovri

Referencing #393

**Comment by fluffypony** [comment]
Done

**Comment by anonimal** [comment]
Great, thanks @fluffypony
