### ISSUE TITLE
ARMv7: SIGILL from OpenSSL: /lib/arm-linux-gnueabihf/libcrypto.so.1.0.0

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#434]
**By submitting this issue, I confirm the following:**

- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

*Place an X inside the bracket to confirm*
- [X] I confirm.

---

My first time running kovri on ARMv7:

```
(gdb) run --log-to-file 0
Starting program: /home/anonimal/kovri/build/kovri --log-to-file 0
Cannot parse expression `.L966 4@r4'.
warning: Probes-based dynamic linker interface failed.
Reverting to original interface.

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
0xb6c31f08 in ?? () from /lib/arm-linux-gnueabihf/libcrypto.so.1.0.0
(gdb) bt
#0  0xb6c31f08 in ?? () from /lib/arm-linux-gnueabihf/libcrypto.so.1.0.0
#1  0xb6c2f870 in OPENSSL_cpuid_setup () from /lib/arm-linux-gnueabihf/libcrypto.so.1.0.0
#2  0xb6fe28bc in call_init (l=<optimized out>, argc=argc@entry=5, argv=argv@entry=0xbefff6f4, env=env@entry=0xbefff70c) at dl-init.c:72
#3  0xb6fe2996 in call_init (env=<optimized out>, argv=<optimized out>, argc=<optimized out>, l=<optimized out>) at dl-init.c:30
#4  _dl_init (main_map=0xb6fff958, argc=5, argv=0xbefff6f4, env=0xbefff70c) at dl-init.c:120
#5  0xb6fd7a84 in _dl_start_user () from /lib/ld-linux-armhf.so.3
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb)
```

OpenSSL: ubuntu xenial 1.0.2g-1ubuntu4 deb from debian-armhf reproducible build on our [v7 build machine](https://build.getmonero.org/builders/kovri-all-ubuntu-arm7).

**Comment by anonimal** [comment]
Note: I **cannot** reproduce this issue on our [cubieboard 2 setup](https://github.com/monero-project/meta/issues/8). So far, all is well on that machine.

**Comment by anonimal** [comment]
I cannot reproduce this issue as it only occurs when ran inside gdb; and this makes sense symbol-wise (AFAICT).

Closing as not kovri-related (can re-open if proven otherwise).

**Comment by bortzmeyer** [comment]
For the record, this behaviour is documented in the OpenSSL FAQ https://www.openssl.org/docs/faq.html#PROG17
