### ISSUE TITLE
Win32/64: uncaught exception when fetching from subscription/reseed server(s) + ARMv8 when updating subscription

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#453]
**By submitting this issue, I confirm the following:**

- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

*Place an X inside the bracket to confirm*
- [X] I confirm.

---

This appears to be purely an cpp-netlib/openssl [upstream issue](https://github.com/cpp-netlib/cpp-netlib/issues/696). *Not* reproducible on [currently supported](https://build.getmonero.org/waterfall) non-windows machines (haven't tested on ARM platforms though).

```
NFO   AddressBookSubscriber: downloading subscription https://downloads.getmonero.org/kovri/hosts.txt ETag:  Last-Modified:
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<std::__exception_ptr::exception_ptr>'

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

Also appears to effect fetching from the reseed server `https://reseed.atomike.ninja/`.

Even if this [proposed patch](https://github.com/cpp-netlib/cpp-netlib/issues/696#issuecomment-255490527) works, I don't see why the fetch would be thrown in the first place (i.e., under similar conditions, it's never thrown on non-windows) except if there was an underlying openssl issue.

More info needed. I'll test the proposed patch soon.

**Comment by anonimal** [comment]
The patch works enough to keep the router online but the underlying issue still appears to be upstream.

When reseeding from `https://reseed.atomike.ninja`:
```
NFO   Reseed: successfuly loaded 8 certificates
NFO   Reseed: fetching stream from https://reseed.atomike.ninja/i2pseeds.su3
ERR   HTTP: caught exception_ptr, rethrowing exception
ERR   HTTP: Dynamic exception type: boost::system::system_error std::exception::what: certificate verify failed
```

When fetching subscription from `https://downloads.getmonero.org`:

```
DBG   AddressBook: picking random subscription from total publisher count: 1
DBG   AddressBookSubscriber: creating thread for download
NFO   AddressBookSubscriber: downloading subscription https://downloads.getmonero.org/kovri/hosts.txt ETag:  Last-Modified:
ERR   HTTP: caught exception_ptr, rethrowing exception
ERR   HTTP: Dynamic exception type: boost::system::system_error std::exception::what: The format of the specified network name is invalid
```

**Comment by anonimal** [comment]
Strangely, this issue only very recently effects the ARMv8 machine (Linaro/Debian Jessie) and *only* during subscription updating (as noticed in #487).

With catch-patch applied:
```
DBG   AddressBook: begin SubscriberUpdateTimer
ERR   AddressBook: publisher(s) already loaded
DBG   AddressBook: picking random subscription from total publisher count: 1
DBG   AddressBookSubscriber: creating thread for download
NFO   AddressBookSubscriber: downloading subscription https://downloads.getmonero.org/kovri/hosts.txt ETag:  Last-Modified:
ERR   HTTP: caught exception_ptr, rethrowing exception
ERR   HTTP: Dynamic exception type: boost::system::system_error
std::exception::what: stream truncated
```

Other platforms (aside from windows) are uneffected. I'll reopen this issue and expand the catch-patch to include all platforms because it's harmless. Ideally, cpp-netlib/cpp-netlib#696 fixes this issue.

@danrmiller has the ARMv8 box undergone any out-of-the-ordinary updates within the past week?

**Comment by danrmiller** [comment]
Yes the armv8 box has had at least openssl updated this week when looking into an unrelated build issue for monero. I will record the previous and current versions, revert, and we can try it again.

**Comment by anonimal** [comment]
Thanks for the speedy response @danrmiller. I'll set time aside this week to test against the reverted openssl version.

**Comment by anonimal** [comment]
Patched in #491, closing.

@danrmiller good news: I cannot reproduce the issue on the reverted openssl. Which two versions are we dealing with? I'm only seeing logs with 1.0.2j.

**Comment by danrmiller** [comment]
yes it was a temporary test with 1.1

**Comment by anonimal** [comment]
Thanks @danrmiller, I've added a note to https://github.com/cpp-netlib/cpp-netlib/issues/696#issuecomment-265813653.
