### ISSUE TITLE
Build: enable coverage for coveralls

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#467]
**By submitting this issue, I confirm the following:**

- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

*Place an X inside the bracket to confirm*
- [X] I confirm.

---

In progress.

**Comment by anonimal** [comment]
Fixed in #468. Worked out the remaining details in private.

**Comment by rakhimov** [comment]
The coverage data needs to exclude the external dependencies.
I couldn't find the submission file in the repo,
so probably @anonimal has it somewhere.
Anyway, this is my current setup to work with Coveralls with the help from [coveralls-lcov](https://github.com/okkez/coveralls-lcov)
```bash
COV_DIR="build/src/CMakeFiles/"
TRACE_FILE="coverage.info"

lcov --no-compat-libtool --directory \
  $COV_DIR -c --rc lcov_branch_coverage=1 -o $TRACE_FILE -q 2> /dev/null
lcov --extract $TRACE_FILE '*/kovri/src/*' -o $TRACE_FILE
coveralls-lcov $TRACE_FILE
```

**Comment by anonimal** [comment]
I've asked devops (@danrmiller) but he's busy with other things at the moment.

**Comment by danrmiller** [comment]
Thanks I'll make these changes and report here

**Comment by danrmiller** [comment]
@rakhimov thanks! We are using gcov and cpp-coveralls so I tried to adjust.

Updated the PR for buildbot: https://github.com/monero-project/meta/pull/20/commits/bbf3d41ca809b2e443499ed52e83ef3913be8671
I ran the updated job: https://build.getmonero.org/builders/kovri-all-ubuntu-amd64/builds/167
Here is what it shows now: https://coveralls.io/jobs/20747927

**Comment by rakhimov** [comment]
@danrmiller Great job! ~80 files are gone from the report.

I think we can cut still more noise from the ~200 file report.
With the current style guide discouraging inline functions in headers (who tests getter/setter anyway ;-)),
most (probably all) headers have 0 relevant lines and 100% coverage in the report.
The only useful info coming from this noise is the number of hits/function calls,
but this information is more helpful for profiling than test coverage.

I guess (with 1 header for 1 impl file) ignoring this noise would reduce the # of files in the report by half.
If you have time, this should be an interesting thing to check out.

Thanks.
