### ISSUE TITLE
Win32: client tunnel ports not binding

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#494]
**By submitting this issue, I confirm the following:**

- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

*Place an X inside the bracket to confirm*
- [X] I confirm.

---

My profound love and passion for all things Microsoft has been reborn, much like: a graceful supple kiss to the cheek, a wafting fragrant spring breeze, the joy of innocent kittens frolicking through a flowerbed, humming birds swirling, tiny birds chirping, mirth and merriment...

Now that the win32 machine is settled/configured for regular testing, it appears that all client tunnels are not binding. This doesn't effect win64 nor any other platform. Interestingly enough, after stopping/starting the router, the IRC client tunnel felt like binding and *did* successfully stream/connect to Irc2P - but that was a fleeting moment: after stopping/starting again, it would not bind.

Info needed - as well as a walk in a park.  **Edit:** JFTR: http/socks proxy ports do bind (but not client tunnels). **Edit:** note: I've never known client tunnels to work on win32 as this is the first time I've started regular testing. There's a slight chance this could be devops related (but I highly doubt that), we'll see.

**Comment by danrmiller** [comment]
Try it now, I've disabled the windows firewall.

**Comment by anonimal** [comment]
No changes (btw, this is localhost bound only).

**Comment by anonimal** [comment]
@danrmiller problem solved, a fix is on the way.

**Comment by anonimal** [comment]
IIRC, behavior is undefined if not properly initialized but some compilers play nicer than others? I still can't reproduce this on other machines despite many repeated attempts. Either way, this should have been initialized to begin with (my fault!!! 😆) - and this doesn't mean that my love for Windows has changed 💐 🌞 😍
