### ISSUE TITLE
Create "What Kovri Does For You" blurb

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#51]
```
~fluffypon      I also think we have to consider putting together an implementation comparison page (something like https://geti2p.net/en/comparison/tor) 
~fluffypon      but not just yet 
~fluffypon      then
&anonimal       And the comparisons will be between kovri and every other i2p router?
~fluffypon      anonimal: yes
```

**Comment by anonimal** [comment]
Related to #8.

**Comment by fluffypony** [comment]
Here's a starting point:

`-` | Kovri | Router 1 | Router 2
---|---|---|---
Roolz | Yes | No | No
Droolz | No | Yes | Yes

**Comment by anonimal** [comment]
After discussing this issue with @fluffypony, we decided to focus on a "What Kovri Does For You" checkbox instead of a complete implementation page. Checked = currently implemented, Unchecked = not implemented / will implement.

I'll send this to https://github.com/anonimal/kovri-site and we can develop the idea if needed. Will probably use a table instead of a checkbox, we'll see what works best.
