### ISSUE TITLE
[feature request] Possibility to use an external I2P router

### ISSUE THREAD

**Issue by ElLamparto** [monero-project/kovri#516]
If one day an i2p router is integrated into Monero, it should be possible to use an external i2p router.

I run i2p. However my band width is limited and I prefer to avoid running two routers at the same time.

Monero should use its internal i2p router by default, but there should be a possibility to disable it and connect to an external one.

**Comment by anonimal** [comment]
Simple solution: you wouldn't run java i2p - you would run kovri instead. Ultimately, you wouldn't need to run two routers anyway. Does that make sense? Also note that kovri will be optional for monero but what you're requesting is something that monero would have to implement, not kovri.

Kovri removes the need to connect to an external non-kovri router but if you really want to push the idea, visit https://github.com/monero-project/monero/issues.
