### ISSUE TITLE
CMake: Ubuntu32 refuses to link -ldl for OpenSSL/cpp-netlib

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#524]
**By submitting this issue, I confirm the following:**

- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

*Place an X inside the bracket to confirm*
- [X] I confirm.

---

For all platforms, ensure all dependencies are not dynamic (except for glibc, openssl, etc.). I've fixed ubuntu, working on the rest.

**Comment by anonimal** [comment]
Accidently posted in https://github.com/monero-project/kovri/issues/362 though it is related:

```
&anonimal Alright, as I mentioned in #monero-dev, the win build is now officially static (minus the usual system32 dll's).
&anonimal The problem being openssl and the fact we *don't* want it static but really have no choice at this time (afaict).
&anonimal So, that just makes for more work for me or whoever wants to keep up with openssl stable releases.
&anonimal (or minimum hot fixes)
&anonimal pigeons: is there a way we could automate some of this task? RSS feed + email notification + triggers buildbot + uploads to wherever? (something like that maybe?)
&anonimal And then there's the question of making openssl static for all non-windows platforms too (for static builds). Maybe update them all in one fell swoop when the time comes if we can get the process automated?
+pigeons ok we can set something up, but seems like something to manually trigger, but still setup the rest of the automation
&anonimal Ok that would work great.
```

**Comment by anonimal** [comment]
As noted in #525, because cmake on ubuntu32 (and only ubuntu32) is refusing to link `-ldl` for openssl/cpp-netlib despite the library being available and the recipe properly set (apparently), I'm going to open a ticket on cmake's gitlab.

Relabeling, reopening.

**Comment by anonimal** [comment]
Opened https://gitlab.kitware.com/cmake/cmake/issues/16547

**Comment by NanoAkron** [comment]
Does this help at all:

http://stackoverflow.com/questions/20131138/cmake-add-ldl-at-end-of-link-stage-of-add-library

`target_link_libraries(ExtremeCUnit dl)`

**Comment by NanoAkron** [comment]
Does this help at all:

http://stackoverflow.com/questions/20131138/cmake-add-ldl-at-end-of-link-stage-of-add-library

i.e. adding `target_link_libraries(library_name dl)`

**Comment by anonimal** [comment]
As noted in https://github.com/anonimal/cpp-netlib/commit/80b46bd62dab4114636ad4f316b5fb404c72aef0 which was referenced in the [cmake issue](https://gitlab.kitware.com/cmake/cmake/issues/16547), it doesn't work in any kovri/cpp-netlib recipes.

**Comment by anonimal** [comment]
Update: the issue is a confirmed CMake issue. The conversation continues in https://gitlab.kitware.com/cmake/cmake/issues/16547.

**Comment by anonimal** [comment]
I've resolved the issue here https://gitlab.kitware.com/cmake/cmake/issues/16547#note_220657
