### ISSUE TITLE
How stable is Kovri currently?

### ISSUE THREAD

**Issue by pwrml** [monero-project/kovri#599]
Hi!

In your experience and understanding, how stable is Kovri currently?

I asked some people and they gave me the double message that on the one hand it's very stable and used in some production environments, but, on the other hand it should be declared as alpha software currently as it not is used beyond those production environments currently.

I want to use Kovri for routing/services only.

Thanks!

**Comment by anonimal** [comment]
There are still open issues which may effect run-time stability but some people may never encounter them. Your best effort is to run 24x7 on your chosen platform, see how she runs, and give feedback.

What we forked from had the audacity to not call themselves anything less than alpha. It was a terribly unfit code-base of which we've done a fair amount of work on: fixing and features, but still have much more to do. Our alpha release is coming up soon - with alpha meaning Kovri is not feature complete though should be good enough for regular testing but **the end-user should know that our rigorous security auditing and [Quality Assurance](https://github.com/monero-project/kovri/blob/master/doc/QUALITY_ASSURANCE.md) has not been completed and will not be completed until beta**.

Please see the FAQ for more info or feel free to PR/contribute to the FAQ or any documentation.
