### ISSUE TITLE
Laptop mode - dynamic ip

### ISSUE THREAD

**Issue by MoroccanMalinois** [monero-project/kovri#607]
---
**By submitting this issue, I confirm the following:**

- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.
---
Referencing #383 
One setting is "i2p.router.net.laptopmode". From the [spec](https://geti2p.net/en/docs/api/i2pcontrol) : 

    *i2p.router.net.laptopmode – [String] Is laptop mode enabled (change router identity and UDP port when IP changes ). If null is submitted, current setting will be returned.

IIUC, if the same router identity appears with multiple ips, one could correlate this identity with these ips. 

PS : i find the option name "laptopmode" misleading, as there is a lot of countries where people have dynamic ips at home. Also, it might deserve a little warning in the doc.

**Comment by SamsungGalaxyPlayer** [comment]
Is there a reason to have "laptop mode" disabled?

**Comment by anonimal** [comment]
@SamsungGalaxyPlayer possibly because there's not enough research on how sustainable the network will be if everyone has it enabled?

**Comment by anonimal** [comment]
NOTICE: THIS ISSUE HAS BEEN MOVED TO GitLab. Please continue the discussion there. See https://github.com/monero-project/kovri/issues/1013 for details.
