### ISSUE TITLE
reload tunnels.cfg when changed

### ISSUE THREAD

**Issue by majestrate** [monero-project/kovri#61]
the router should periodically check tunnels.cfg for changes and update the router to reflect these changes instead of requiring restart.

**Comment by majestrate** [comment]
I will work on this.

**Comment by anonimal** [comment]
Excellent, thanks.

This is related to #42.  In theory, the router wouldn't actually be restarted: SIGHUP would simply update the variable map and call the appropriate i2p::context members functions.

I agree that we should implement this ticket but we should also try to wrap-up SIGHUP handling as well or rethink our current design all-together.

**Comment by anonimal** [comment]
Merging with #96. Closing as duplicate.
