### ISSUE TITLE
Efficient management of options w/o duplication

### ISSUE THREAD

**Issue by rakhimov** [monero-project/kovri#611]
There's potential duplication of kovri options in:

1. Boost program options
2. kovri.conf
3. Bash completion script
4. man page

The manual management is error-prone as discussed in #610 .
We need to choose only one to manage
and generate the others with automation.
Keep it DRY and on SPOT :)

Boost program options or ``kovri --help`` seems to be the best candidate for being one true source.
However, it currently lacks important information like argument types and option descriptions.
With this information complete, it should be possible to cover the other formats,
for example, with ``help2man`` or bash scripts.

Helpful info:
- [how to add type info to boost arg](http://stackoverflow.com/questions/1249646/when-using-boostprogram-options-how-does-one-set-the-name-of-the-argument/39934452#39934452)

---
**By submitting this issue, I confirm the following:**

- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.
---

**Comment by anonimal** [comment]
NOTICE: THIS ISSUE HAS BEEN MOVED TO GitLab. Please continue the discussion there. See https://github.com/monero-project/kovri/issues/1013 for details.
