### ISSUE TITLE
Works on OpenBSD now?

### ISSUE THREAD

**Issue by mlmikael** [monero-project/kovri#618]
Hi @anonimal , does Kovri build and run on OpenBSD now?

**Comment by anonimal** [comment]
Yes. Download the binary here https://github.com/monero-project/kovri#nightly-releases-bleeding-edge. As for the dynamic build, I am still waiting for @noloader to merge or comment further on https://github.com/weidai11/cryptopp/pull/398.  Until then, you can build from the repo with `gmake release-static && gmake install`.

Referencing https://github.com/monero-project/kovri/issues/590#issuecomment-288895759

**Comment by noloader** [comment]
@anonimal , @mlmikael,

Ack, thanks. I merged the patch this morning.

My apologies for the delay. In the future, feel free to email me at *noloader, gmail account*. Things fall off my radar on occasion. Sometimes I need a nudge to get pointed in the right direction.

**Comment by anonimal** [comment]
@noloader Hi, thanks for the ACK and note about emailing, will do.
