### ISSUE TITLE
Reseed: "unknown host" randomrng.ddns.net

### ISSUE THREAD

**Issue by MoroccanMalinois** [monero-project/kovri#624]
---
**By submitting this issue, I confirm the following:**

- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.
---

One of the reseed servers seems completely down. 
The domain randomrng.ddns.net don't resolve, so it looks more than just a temporary failure.

**Comment by anonimal** [comment]
I've yet to receive an official notice from the reseed maintainer's list. I'll send a message.

**Comment by anonimal** [comment]
Response received, the reseed maintainer is looking into the issue.
