### ISSUE TITLE
Core: router context + RI rewrite/refactor

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#627]
WIP as noted in #617 #621 #623 #626. Ticketing for housekeeping.

WIP in pursuit of isolating #187 (and because RI impl was in bad shape / unmaintainable).

---
**By submitting this issue, I confirm the following:**

- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.
---

**Comment by anonimal** [comment]
Added router context because it's in just as bad shape.

**Comment by coneiric** [comment]
Small cheat-sheet for RI sizes: [router_info_size.md](https://gist.github.com/coneiric/a2bc40172cd7a5465ba8e2b527b1c0c5)

Some of the maximums are the max allowed by the size byte(s), when the specification doesn't otherwise limit. Should we set a cap in those cases?

**Comment by anonimal** [comment]
Cap as in capability or cap as in top/hat limit?

**Comment by anonimal** [comment]
>router_info_size.md

I think this would be great in the moneropedia (see monero-site) or perhaps something in kovri-docs or kovri-site?

**Comment by coneiric** [comment]
> Cap as in capability or cap as in top/hat limit?

Cap as in limit to total `RouterInfo` size we'll accept. Otherwise, that ~17MB max total size looks like a potential DoS vector.

> I think this would be great in the moneropedia (see monero-site) or perhaps something in kovri-docs or kovri-site?

Sure, I can make a PR to monero-site and kovri-docs. Is kovri-site still pulling from kovri-docs? If not, I can make a PR there as well.

**Comment by anonimal** [comment]
>Is kovri-site still pulling from kovri-docs?

Yes, it should be. This is still open though https://github.com/monero-project/kovri-site/issues/73.

**Comment by anonimal** [comment]
https://github.com/coneiric/kovri/pull/2

**Comment by anonimal** [comment]
https://github.com/coneiric/kovri/pull/4

**Comment by anonimal** [comment]
NOTICE: THIS ISSUE HAS BEEN MOVED TO GitLab. Please continue the discussion there. See https://github.com/monero-project/kovri/issues/1013 for details.
