### ISSUE TITLE
`make upnp` is not a target in the Makefile

### ISSUE THREAD

**Issue by itdaniher** [monero-project/kovri#649]
It's mentioned in the build docs [Here](https://github.com/monero-project/kovri/blob/master/doc/BUILDING.md#other-options-you-can-use-in-place-of-step-2), but is not listed in the [optional builds in the Makefile.](https://github.com/monero-project/kovri/blob/master/Makefile#L172)

Something like:

```
# UPnP
upnp: deps
	$(eval cmake-kovri += $(cmake-upnp))
	$(call CMAKE,$(build),$(cmake-kovri)) && $(MAKE)
```

added to the makefile would resolve this issue.

I'm currently building after running `cmake -D WITH_UPNP=ON .`

Cheers!

**Comment by anonimal** [comment]
Hi @itdaniher, it was removed long ago but the docs were never updated. It can easily be re-added though. Please feel free to submit a PR.

Note: `make all-options` is also available.

**Comment by itdaniher** [comment]
Thanks @anonimal!
