### ISSUE TITLE
Crypto++ and upcoming change for byte definition due to C++17

### ISSUE THREAD

**Issue by noloader** [monero-project/kovri#675]
The Crypto++ library is getting ready to change its definition for `byte`. The short of it is, Crypto++ `byte` and C++17 `std::byte` can cause compile failures due to ambiguous declarations; and the behavior of `byte` and `std::byte` are incompatible. More information can be found at:

* [std::byte](https://www.cryptopp.com/wiki/Std::byte) on the Crypto++ wiki

* [Issue 442, Test C++17 byte change with dry runs from various projects](https://github.com/weidai11/cryptopp/issues/442)

We are looking for testers to provide early feedback. Please see:

* [Issue 442, Test C++17 byte change with dry runs from various projects](https://github.com/weidai11/cryptopp/issues/442)

Recommendations for user programs which rely the library can be found at:

* [std::byte | Fixing Programs](https://www.cryptopp.com/wiki/Std::byte#Fixing_Programs) on the Crypto++ wiki

The change will exist in Master, and then be part of the Crypto++ 6.0 release. The change needs a major version bump because it is so disruptive to user programs. We would like to release Crypto++ in the next month or two.

My apologies for opening an issue. Please label it as an enhancement or feature request.

**Comment by anonimal** [comment]
Hi @noloader. I've been watching this issue unfold and we remain unaffected. Thank you for opening the issue 😄
