### ISSUE TITLE
Signup for CodeDocs.xyz

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#69]
We currently have a Doxygen build option but this would be a nice feature for easy online reference.

From the [site](https://codedocs.xyz/):
> CodeDocs will generate and publish documentation for you, using Doxygen. It's free and easy to setup with your public GitHub repositories.

Monero would simply visit the site and signup via GitHub oauth. As for post-signup configuration, I have no idea what would be needed - so we'll see what needs to be done when we get there.

**Comment by paulnovo** [comment]
Hello, I created codedocs and noticed this issue. @anonimal is correct, you just need to sign on to the service and enable the kovri repository. I created a pull request #78 that adds custom doxygen settings that closely match your Doxyfile.in. You can see the results on my fork:

  https://codedocs.xyz/paulnovo/kovri/

The pull request also adds a badge to your README.md that points to:

  https://codedocs.xyz/monero-project/kovri/

This currently won't work until you enable the repository in CodeDocs. Hope this helps, and let me know what you think.

**Comment by fluffypony** [comment]
Ok done - it says "Generating documentation", so I guess now we wait.

**Comment by anonimal** [comment]
JFTR: the conversation branched off to the [PR](https://github.com/monero-project/kovri/pull/78).
