### ISSUE TITLE
[Subscription Request] aceti.i2p

### ISSUE THREAD

**Issue by alvinjoelsantos** [monero-project/kovri#694]
`vmkrvrqpwt4p3i75kfuvlpd4wjvbsadiim6ux76vjmwo6p4mz4ta.b32.i2p
TK-47sEkAqixGqLcglBk9gOg2CJ-ig2JBya24ESVBheCPH8gryh8oNRIFlgyrWXpRS0NRFHnfz3bjOcHrVwqk1kpK~QpcB06gmDn4jUWO4pDS9QD6dSak2M4TDADWYxBzVUiLelKYf-tajKR25tRBwYn6gwnundxkwOtPHiljcuALbkXKlzhKhUCQUmOCAZ4SKvK78kqEJxeGI~YsWvPhbwKfNh6h7~71X2VqKkRa4U1iQ7p1rV9gj5H6UUNOtip-ykblPQdOjNaYzXIAW1LnBgoRuD6sv1yGizphZDQ5sogM65egZTvAG5MRcrapktK8mvF-3GDMb1AXyoxwwc7xL5T3RWWHFcuIgaP2ndzxdYQF1qY98pGJIPuNFfXkgld8L7lDWENUinXkBfEyDO1Asq6AXQ0vEae40du2qzH2LXmUBE~3utY3v1wSJffq7nlI7jblYe4p8NOAj5Nw-dv-CRCjbm3SIhOGSAO8wFzx7ZQyKqfmpjmN0X6oqj0wHwiBQAEAAEAAA==`

**Comment by anonimal** [comment]
@alvinjoelsantos will this site work without javascript enabled?

**Comment by alvinjoelsantos** [comment]
yes, i2p/onion version will have no javascript

**Comment by anonimal** [comment]
This issue will close automatically once #695 is merged. I'd still like to test do a live-test.
