### ISSUE TITLE
mutex lock failed: Invalid argument

### ISSUE THREAD

**Issue by selsta** [monero-project/kovri#697]
OS: macOS 10.13

When pressing CTRL+C about 1 second after starting the program, it does not exit properly. This is not 100% reproducible because of timing.

Full logs: https://gist.github.com/anonymous/f91b3daf7628cc070e73bf3e1563f088

**Comment by wqking** [comment]
I can't visit gist.github.com for now.
I created another issues about Ctrl+Break. #796
Maybe we need to redesign how the CLI exits?

**Comment by anonimal** [comment]
> Maybe we need to redesign how the CLI exits?

Though I can't reproduce, this is more likely to be a threading issue between the shutting down of library components (transports and tunnels for example) - not application level handling.

**Comment by anonimal** [comment]
NOTICE: THIS ISSUE HAS BEEN MOVED TO GitLab. Please continue the discussion there. See https://github.com/monero-project/kovri/issues/1013 for details.
