### ISSUE TITLE
Write better tests.

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#7]
We need better tests - for everything.

- Crypto unit tests that cover *all* crypto used: 2dc4d74 // In Progress
- More, TODO

**Comment by majestrate** [comment]
I'll take a wack at adding unit tests for RSA DSA and ELG

**Comment by majestrate** [comment]
IMO, `src/tests/unit_tests/Crypto.cpp` should be split up into tests for each crypto component, 1 for eddsa, ecdsa, rsa, dsa, elg, aes... Thoughts?

**Comment by EinMByte** [comment]
@majestrate I agree, but maybe make a directory `crypto` containing all those files.

**Comment by majestrate** [comment]
that sounds like a plan.

**Comment by anonimal** [comment]
```&anonimal | and #7 is vague, not release-related, I want to close and reopen issues more specific to test cases.```
