### ISSUE TITLE
Build: Windows not bundling OpenSSL statically (again)

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [monero-project/kovri#711]
---
**By submitting this issue, I confirm the following:**

- I have read and understood the contributor guide in [kovri-docs](https://github.com/monero-project/kovri-docs).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.
---

I receive the following error when running the latest Win64 Kovri release [#255](https://build.getmonero.org/builders/kovri-static-win64/builds/255):

"The code execution cannot proceed because LIBEAY32.dll was not found. Reinstalling the program may fix this problem."

I then get the same error for SSLEAY32.dll.

It shows up when running both kovri.exe and kovri-util.exe, even in admin mode.

**Comment by anonimal** [comment]
Hi @SamsungGalaxyPlayer.

Somewhere between X months after #525 and Y months ago, the win build stopped bundling openssl statically. Your reported issue is caused by that issue. I estimate a 99.9% probability that the issue is CMake related.

CMake is a huge pain and has been problematic with every project I've encountered that uses it. I've had the *opening* of this issue on my TODO for a while so I'll simply rename this issue to address both problems.

**Comment by anonimal** [comment]
```
@anonimal       pigeons pigeons1[m] interestingly, I can't reproduce kovri/#711 on the win64 build machine nor on a separate win64 machine.
@anonimal       How could buildbot have any effect in this area?
```

Pinging @danrmiller.

Note: this *used* to be reproducible at time of the opened issue but this is no longer the case.

**Comment by anonimal** [comment]
Dumping shared object deps against [latest build](https://build.getmonero.org/builders/kovri-static-win64/builds/359) shows that the problem persists.

**Comment by anonimal** [comment]
Dumping shared object deps against [latest build](https://build.getmonero.org/builders/kovri-static-win64/builds/359) shows that the problem persists (at least in buildbot only).

@SamsungGalaxyPlayer can you clone and `make release-static && ldd ./build/kovri.exe` then paste the `ldd` output here?

**Comment by SamsungGalaxyPlayer** [comment]
Here you go: https://paste.fedoraproject.org/paste/3yANRiOVoL-Nha8TNChVWQ

**Comment by anonimal** [comment]
Thanks @SamsungGalaxyPlayer. This confirms that the static build works as expected and that something appeares to be problematic with our build-system backend. Referencing https://github.com/monero-project/meta/issues/154.

**Comment by danrmiller** [comment]
I get the same unexpected dynamic linking of ssl when manually running make release-static on that machine.

I've added 2 things to help figure it out. VERBOSE=1 is set so you can see the compiler commands in the buildbot stdio log, and the CMakeOutput.log is highlight to the web ui.

https://build.getmonero.org/builders/kovri-static-win64/builds/362

I think what I'll do is setup a new VM for kovri. I don't want to mess up any of the other jobs right now reinstalling/upgrading SSL.

**Comment by anonimal** [comment]
>I get the same unexpected dynamic linking of ssl

Is it the win64 machine that I have access too? I was referring to whichever one I have access to (I thought it was the build machine).

**Comment by anonimal** [comment]
>I think what I'll do is setup a new VM for kovri.

Thank you. I'm also wondering if removing `~/.cmake` on the build machine will have any effect.

**Comment by anonimal** [comment]
Referencing https://github.com/monero-project/meta/issues/154#issuecomment-353810733.

**Comment by anonimal** [comment]
Resolved in https://github.com/monero-project/meta/issues/154#issuecomment-360022918.
