### ISSUE TITLE
Testnet: internal HTTP/S webserver for publishing subscription

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#718]
Opposing approaches to a resolution:

1.
```
@anonimal cpp-netlib has an http/s server API. It seems trivial to implement.
@anonimal We can run a testnet-only server to host as an addressbook publisher.
@anonimal This way we don't do anything crazy like try to setup a webserver within docker for something this small.
@anonimal I say this because right now we are polling downloads.getmonero.org for our default subscription,
@anonimal and, even within testnet, these requests are going live onto the internet so, Nth requests to that host at the same == not very nice.
@anonimal The host is also hardcoded so I think it's best to take advantage of creating a realistic environment rather than having everything be customized.
@anonimal (when we want to change publisher to https://127.0.0.1, we simply > the new host into publishers.txt after we copy resources to workspace. this will override hardcoded value)
```

2.
```
@anonimal Hmm, on 2nd thought, MoroccanMalinoi-,
@anonimal but easier to simply setup a testnet network webserver? Probably, and we would avoid furthering our dependency upon a library dependency.
@anonimal We would just have to adjust the webserver config after we've acquired appropriate network octets, then copy over, etc.
@anonimal The C++ in me wants to get away from Docker but the Docker in me wants to get away from C++ for this task ;)
```

Both have selling points, but which has more virtue? Note: a WebUI is not a virtue, so please don't.

**Comment by MoroccanMalinois** [comment]
tbh, no preference here, both seems ok and trivial to implement. To serve a simple file/directory w/o https using docker :

    docker run -v /path/to/host/dir:/usr/share/nginx/html:ro -p 80 nginx

If https is required, i think it will add about the same amount of work for both methods (specifying certs locations ...) . I'm not familiar with this part of the code, maybe there is some "funny" tests to try, where one method would have any advantage ?

**Comment by anonimal** [comment]
In hindsight, considering the lack of cpp-netlib development (on part of their lead devs), I think we shouldn't rely too much on cpp-netlib and instead simply stick with a webserver instance.

This webserver will serve via internal clearnet and will also host a kovri instance so we can test in-net subscriptions. We should keep https functionality and, while on-topic (and for the sake of testnet), perhaps extend `--reseed-skip-ssl-check` to subscription fetching (then rename the cli option).
