### ISSUE TITLE
What time  integrated with monero, What's the plan?

### ISSUE THREAD

**Issue by maogo** [monero-project/kovri#743]
---
**By submitting this issue, I confirm the following:**

- I have read and understood the contributor guide in [kovri-docs](https://github.com/monero-project/kovri-docs).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.
---

**Comment by anonimal** [comment]
@maogo Questions go to [support](https://github.com/monero-project/kovri#support). This is a code issue tracker.
