### ISSUE TITLE
FreeBSD build

### ISSUE THREAD

**Issue by fabianfrz** [monero-project/kovri#782]
Kovri does currently build on FreeBSD 11.1 so the badge visible via the Readme is misleading.

Here is some proof of a successful build:
![screenshot_20171229_215859](https://user-images.githubusercontent.com/3713914/34447366-7a9f99ec-ece3-11e7-8944-af1248f3041f.png)

**Comment by anonimal** [comment]
The buildbot freebsd machine is offline right now. That build fails because of backend issues. Pinging @danrmiller.

**Comment by anonimal** [comment]
Resolved in https://github.com/monero-project/meta/issues/160.
