### ISSUE TITLE
Allow for more bandwidth limit options

### ISSUE THREAD

**Issue by robsmith11** [monero-project/kovri#783]
According to the comments in `Kovri.conf`, the only options for bandwidth are 32 Kbits/sec or unlimited.  Those two options are rather extreme, so it would be nice to have more flexibility.

Also, I believe the `L` description may be incorrect..  32 KBytes/sec sounds more reasonable than 32Kbits/sec.

**Comment by anonimal** [comment]
>Also, I believe the L description may be incorrect

Yes, typo. Also, another note: the parameter is an implementation detail and does not correlate with spec-defined bandcaps. 'L' will be removed so bandcaps can specifically be passed (these bandwith capabilities have finer granularity).

The bandcaps params issue hadn't been formally opened though it was always noticed in passing. We'll go ahead and keep track of that now, thanks.

**Comment by anonimal** [comment]
NOTICE: THIS ISSUE HAS BEEN MOVED TO GitLab. Please continue the discussion there. See https://github.com/monero-project/kovri/issues/1013 for details.
