### ISSUE TITLE
[Request] Support SIGBREAK on Windows terminals

### ISSUE THREAD

**Issue by wqking** [monero-project/kovri#796]
OS: Win10

Currently when there is anything wrong in the CLI and after "Good bye" message, the terminal just hangs and Ctrl+Break doesn't exit the CLI too. (Ctrl+Break) doesn't work any time during the CLI running.

By reading the comment in file client/instance.cc, in the function `void Instance::Initialize()`, seems currently CLI doesn't work well with signals and can't exit gracefully.

If it's an issue and need to solve, I'm happy to work on it, though I guess it may be not as easy as it supposed to be.

---
**By submitting this issue, I confirm the following:**

- I have read and understood the contributor guide in [kovri-docs](https://github.com/monero-project/kovri-docs).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.
---

**Comment by anonimal** [comment]
>seems currently CLI doesn't work well with signals and can't exit gracefully.

This is not true. You are suggesting we handle `SIGBREAK`, which we don't. MSYS2 should be able to handle `SIGINT` and I have seen many successful exit on windows.

Please provide more terminal information and reasoning why you want to handle `SIGBREAK`. I wouldn't be surprised if this is a windows-specific request.

**Comment by wqking** [comment]
I tried that Ctrl+C works on Ubuntu 16.0.4, though it didn't for my Win10 MSys2 built version.
Seems it may be a compatibility problem on Windows or caused by my build environment.
I suggest to close this issue for now, but we need to test Windows compatibility thoroughly before the Alpha release.

**Comment by anonimal** [comment]
>we need to test Windows compatibility thoroughly before the Alpha release.

Yes.
