### ISSUE TITLE
 arm7-linux build won't run on Raspberry Pi 3

### ISSUE THREAD

**Issue by burbite** [monero-project/kovri#807]
Recent arm7-linux build won't run on a Raspberry Pi 3 under current Raspbian.
      kovri-ecffd7b-Linux-armv7l-2018.02.04
requires obsolete versions of libssl and libcrypto (1.0.0)
My system has version 1.0.2 of both installed.
```
pi@raspberrypi:~/bin $ ldd ./kovri
        linux-vdso.so.1 (0x7eef6000)
        /usr/lib/arm-linux-gnueabihf/libarmmem.so (0x76f8a000)
        libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0x76f61000)
        libssl.so.1.0.0 => not found
        libcrypto.so.1.0.0 => not found
        libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0x76ee2000)
        libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x76da3000)
        /lib/ld-linux-armhf.so.3 (0x76fa0000)
```
Forced symlinks to libs in version 1.0.2 also fail
Please fix when possible.

```
pi@raspberrypi:~/bin $ ldd ./kovri
./kovri: /lib/arm-linux-gnueabihf/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by kovri)
./kovri: /lib/arm-linux-gnueabihf/libssl.so.1.0.0: version `OPENSSL_1.0.0' not found (required by ./kovri)
```
Cheers
---
**By submitting this issue, I confirm the following:**
- I have read and understood the contributor guide in [kovri-docs](https://github.com/monero-project/kovri-docs).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.
---

**Comment by danrmiller** [comment]
Those files are only a convenience anonimal requested so he can test them on the same box they were built on. If you can't build your own, you can try the unofficial testing static builds.
https://build.getmonero.org/downloads/kovri-latest-linux-armv7.tar.bz2
https://build.getmonero.org/downloads/kovri-latest-linux-armv7.tar.bz2.sha256sum.txt

**Comment by anonimal** [comment]
@burbite like Dan said, use the nightly builds as described in our README. Fishing around our buildbot waterfall is not recommended.

**Comment by burbite** [comment]
I never fished around, always tried the latest-linux-armv7-whatever: as far as I can tell, does not work for me as described above. Sorry for bothering your guru heads guys, as newbie just tried here as no forum seems to exist. Good luck, bye

**Comment by anonimal** [comment]
>as far as I can tell, does not work for me as described above

I cannot reproduce, not even on a separate arm machine.
