### ISSUE TITLE
HTTP Proxy / AddressBook: ensure that jump service doesn't save already-known addresses

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#814]
---
**By submitting this issue, I confirm the following:**

- I have read and understood the contributor guide in [kovri-docs](https://github.com/monero-project/kovri-docs).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.
---

i.e., the address exists in addressbook but our jump service handler blindly writes to disk regardless. This issue is about disk handling and not in-memory addresses (we use a map to store in-memory addresses and access/set the elements via `operator[]`).

This may as well be an addressbook issue because not allowing dups should be an addressbook responsibility. TBD. Referencing #305.

**Comment by coneiric** [comment]
> This may as well be an addressbook issue because not allowing dups should be an addressbook responsibility.

Was thinking along similar lines, putting the check in `AddressBookStorage::AddAddress` and `AddressBook::InsertAddressIntoStorage`.

Going to start work on a PR for some address book TODOs related to #305, and will make this bug a priority.
