### ISSUE TITLE
RI SSU IPv6 address not properly updated when NTCP is disabled

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#826]
---
**By submitting this issue, I confirm the following:**

- I have read and understood the contributor guide in [kovri-docs](https://github.com/monero-project/kovri-docs).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.
---

A hexdump of `router.info` confirms that, despite IPv6 being enabled and used in SSU, our RI is not properly updated when `--enable-ntcp 0` (the entire IPv6 fields are missing). When default NTCP is enabled (`--enable-ntcp 1`) and IPv6 is enabled, the RI is properly updated for both transports.

This issue is not related to #776 though is in a similar area.

**Comment by brbzull0** [comment]
What's the role of `--host` when `--enable-ssp` or `--enable-ntcp` is set to 0? The provided host may not match the ones in the existing RI and if `--enable-ntcp 0` is used we are disabling NTCP for an existing host that didn't match the one in the  `--host` flag.

**Comment by MoroccanMalinois** [comment]
@brbzull0 Option `--host` is used for socket binding, i.e. choosing wich network interface to use, just like any "classic" TCP/UDP service. It's conceptually unrelated to SSU or NTCP. 

> The provided host may not match the ones in the existing RI

Don't know about NTCP, so i'll only speak about SSU. Correct, but when SSU is enabled, there is a mechanism to detect the external IP of the host (First thing done after the reseed). The router will then update its RI accordingly and republish.

**Comment by anonimal** [comment]
@brbzull0 `--host` is essentially deprecated but cannot be fully deprecated until we implement external NTCP-only IP detection (which would also resolve #776). There may be other arguments for keeping `--host` but I can't think of any off the top of my head.

Sidenote: we *must* have at least 1 transport running and I notice that we allow disabling *both* transports. I'll open a new issue.

**Comment by anonimal** [comment]
NOTICE: THIS ISSUE HAS BEEN MOVED TO GitLab. Please continue the discussion there. See https://github.com/monero-project/kovri/issues/1013 for details.
