### ISSUE TITLE
Testnet: unable to disable transports

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#832]
---
**By submitting this issue, I confirm the following:**

- I have read and understood the contributor guide in [kovri-docs](https://github.com/monero-project/kovri-docs).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.
---

As noted in https://github.com/monero-project/kovri/pull/831#discussion_r173378082, the issue is within the utility binary:

>This reminds me that there is a bug that I've been meaning to address. As found on testnet, when disabling transports, they are not appropriately disabled.

The fix should be trivial: expand RI option arguments to include transports and actually apply them.

**Comment by brbzull0** [comment]
Is this related to this part of the code( at least one of the many):
https://github.com/monero-project/kovri/blob/4e0fabbec2df1d8c619249d2b4ebefc63710e85c/src/core/router/context.cc#L130

where `RemoveTransport()` is applying the change  to the member RI( which yet wasn't populated?) and not to the existing RI (from disk)?

_The behavior I'm mentioning happen when running  the router._

**Comment by anonimal** [comment]
I should clarify: this issue is regarding RI creation with the utility binary, not the actual daemon. The daemon's parameters are set during testnet creation but the RI's transports aren't properly set. The fix should be as simple as expanding options here https://github.com/monero-project/kovri/blob/master/src/util/routerinfo.cc#L54 and applying here https://github.com/monero-project/kovri/blob/master/src/util/routerinfo.cc#L129.

The time it took to write this issue was about the same time I could've spent sending the PR. I wanted to use the new interface that would come with #831 though. If we end up spending more time on #831 then I'll just patch this issue this week.
