### ISSUE TITLE
HTTP Proxy: Improve Code Style & Organization in HTTPMessage

### ISSUE THREAD

**Issue by coneiric** [monero-project/kovri#844]
---
**By submitting this issue, I confirm the following:**

- I have read and understood the contributor guide in [kovri-docs](https://github.com/monero-project/kovri-docs).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.
---

There are a number of glaring style issues with `HTTPMessage`. Data members should be private, needs new getters/setters for those data members, HTTP + URI components need their own structs, etc.

References #340.

**Comment by anonimal** [comment]
NOTICE: THIS ISSUE HAS BEEN MOVED TO GitLab. Please continue the discussion there. See https://github.com/monero-project/kovri/issues/1013 for details.
