### ISSUE TITLE
HTTP Proxy: Separate Saving Jump Service Addresses from Message Processing

### ISSUE THREAD

**Issue by coneiric** [monero-project/kovri#845]
---
**By submitting this issue, I confirm the following:**

- I have read and understood the contributor guide in [kovri-docs](https://github.com/monero-project/kovri-docs).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.
---

After IRC collaboration with @anonimal & @brbzull0, it seems to me that `HTTPMessage::SaveJumpServiceAddress` should really be its own async proxy handler, `HTTPProxyHandler::SaveAddress`.

Refactoring saving addresses as a proxy handler will decouple HTTP message processing from `AddressBook`'s timer + mutex (allowing us to get rid of the hack needed in #838).
  
References #340 & #844.

**Comment by coneiric** [comment]
Would it be better design to have the handler send the address over the socket as a NetDB `DatabaseStoreMessage`, or directly insert to the AddressBook?

Thought you might have been hinting at the former on IRC @anonimal:
```
@anonimal Right off the bat, IMHO that should be at least 4 different classes. The socket/handler could hypothetically be templated, not specific to HTTP but we'll ignore that for now.
 @anonimal From there you can almost certainly decouple the work even further.
 @anonimal In that scheme, I don't see a reliance on inheritance but really there are multiple ways to deal with the issue.
 @anonimal Did that make sense?
 @anonimal Notice how I left out addressbook and storage, etc. This is intentional.
```

**Comment by anonimal** [comment]
NOTICE: THIS ISSUE HAS BEEN MOVED TO GitLab. Please continue the discussion there. See https://github.com/monero-project/kovri/issues/1013 for details.
