### ISSUE TITLE
AddressBook: new address book entry container

### ISSUE THREAD

**Issue by coneiric** [monero-project/kovri#848]
---
**By submitting this issue, I confirm the following:**

- I have read and understood the contributor guide in [kovri-docs](https://github.com/monero-project/kovri-docs).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.
---

Add a container class for individual address book entry (host-address) pairs.

Will create an interface for passing individual references or collections to/from `AddressBook`. New class will be similar to [AddressBookEntry](https://github.com/monero-project/kovri/blob/master/tests/unit_tests/client/address_book/impl.cc#L47), generalized to be useful in more contexts.

**Comment by anonimal** [comment]
>similar to

If you're going to use `public` `private` class access modifiers and not treat the class as a POD type, then use as class and not a struct. https://github.com/monero-project/kovri/blob/master/tests/unit_tests/client/address_book/impl.cc#L49

**Comment by coneiric** [comment]
> not treat the class as a POD type

I'm not opposed to treating it as a POD type. That would make porting easier, IIUC.
For simple classes/structs like this, is that a better general design?

**Comment by anonimal** [comment]
>is that a better general design?

Basic C++. Lookup what POD means.

**Comment by coneiric** [comment]
> what POD means

Right, I was more asking about if it was worth it to convert `AddressBook::Entry` to a POD type.

Short answer: no. 

Tried some unfruitful experiments, and it's just cleaner as a class. It just looked too heavy with the extra code to convert `kovri::core::IdentHash` + `std::string` to trivial types (and back).

**Comment by anonimal** [comment]
Resolved in #852.
