### ISSUE TITLE
Plugin/interface integration

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#86]
Any plugins/interfaces should adhere to the following minimum requirements:
1. No element of Kovri security or essential functionality should be compromised by the plugin/interface API.
2. core I2P router functionality should _not_ be changed _for_ the plugin/interface API. Instead, the API must adhere to the state of Kovri.
3. If the plugin requires Kovri to be reworked, then that is an issue with Kovri and a related ticket should be opened and subsequent PRs made within their respective topic branches.
4. In-progress or early plugin/interface implementations should work within `src/contrib/api` and configuration files in `pkg/contrib`. Mainline plugin/interface API functionality should work within `src/api` and configuration files within `pkg`. If the plugin/interface needs to extend beyond those respective layouts, see point 3 above. 
5. While any plugin/interface may be helpful to some, it may not be in the best interest of Kovri. If contributors keep this in mind, it may help them fine-tine their ideas.

**Comment by anonimal** [comment]
i2lua was proposed in #81. Though in its early-stages, I think it *should* be in the codebase.

**Comment by majestrate** [comment]
> core I2P router functionality should not be changed for the plugin/interface API. Instead, the API must adhere to the state of Kovri.

-1, that's the entire point of i2lua, it gives researchers and experimenters the ability to tweak core functionality.
