### ISSUE TITLE
Restore PrintLog logging backend

### ISSUE THREAD

**Issue by majestrate** [monero-project/kovri#89]
The entire point of the logging boilerplate is that is abstracts out how logging works, the PrintLog backend was removed in https://github.com/monero-project/kovri/commit/b0ec89c261770277929f3990562741d337fff7ad , please restore it and stop removing features without discussion.

**Comment by anonimal** [comment]
When it becomes necessary to boilerplate the logger, we should do so - and we should do it better than previously proposed. Until then, 7 files for 3 small classes is "redtape".
