### ISSUE TITLE
'kovri -h' prints 3 error lines at end of output

### ISSUE THREAD

**Issue by Wuodan** [monero-project/kovri#899]
---
**By submitting this issue, I confirm the following:**

- I have read and understood the developer guide in [kovri-docs](https://github.com/monero-project/kovri-docs).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.
---
Here's my output:

> [2018-06-12 01:10:03.077251] [0x000072484dc80780] [info]    
> 
> system:
  --host arg (=127.0.0.1)
  -p [ --port ] arg (=0)
  --data-dir path (=/root/.kovri)
  -s [ --service ] arg
  -d [ --enable-daemon ] 
  --disable-console-log 
  --disable-file-log 
  --disable-color-log 
  --enable-auto-flush-log 
  --log-level arg (=3)
  --log-file-name path
  -c [ --kovriconf ] path
  -t [ --tunnelsconf ] path
> 
> 
> network:
  --enable-ipv6 
  --enable-floodfill 
  -b [ --bandwidth ] arg (=L)
  --disable-ssu 
  --disable-ntcp 
  -r [ --reseed-from ] arg
  --disable-https 
  --disable-su3-verification 
> 
> 
> client:
  --httpproxyport arg (=4446)
  --httpproxyaddress arg (=127.0.0.1)
  --socksproxyport arg (=4447)
  --socksproxyaddress arg (=127.0.0.1)
  --proxykeys arg
  --i2pcontrolport arg (=0)
  --i2pcontroladdress arg (=127.0.0.1)
  --i2pcontrolpassword arg (=itoopie)
> 
> [2018-06-12 01:10:03.077350] [0x000072484dc80780] [error]   Configuration: standard exception: 'for more details, see user-guide or config file'
[2018-06-12 01:10:03.077365] [0x000072484dc80780] [error]   Instance: standard exception: 'for more details, see user-guide or config file'
[2018-06-12 01:10:03.077383] [0x000072484dc80780] [error]   DaemonSingleton: Configure: standard exception: 'for more details, see user-guide or config file'

From IRC:
<anonimal> Those are just ctor function try blocks throwing because a real option was called. Help is thrown in with any invalid command, that could be cleaned up

**Comment by anonimal** [comment]
> Those are just ctor function try blocks throwing because a real option was called. Help is thrown in with any invalid command, that could be cleaned up

Yes, but I typo'd: s/real option was called/real option was *not* called/

**Comment by anonimal** [comment]
https://github.com/monero-project/kovri/pull/902 should patch for now.
