### ISSUE TITLE
Official I2P Mirror for Kovri

### ISSUE THREAD

**Issue by majestrate** [monero-project/kovri#90]
We should have a mirror of the source code (and maybe dependencies too) available via i2p such that kovri can be built from inside i2p without touching anything else.

**Comment by majestrate** [comment]
A mirror is at http://git.psi.i2p/psi/kovri which I run but it's read only and "not official".

**Comment by fluffypony** [comment]
Maybe we should setup an official Monero GitLab that mirrors GitHub, and then make that available on i2p. Thoughts?

**Comment by majestrate** [comment]
That would be great, and would also provide access to monero's source too.

**Comment by anonimal** [comment]
> Maybe we should setup an official Monero GitLab that mirrors GitHub, and then make that available on i2p. Thoughts?

1. Branching away from GtiHub will only make development more difficult. Asking new contributors to make a separate account for the sole purpose of kovri/Monero is an unneeded hurdle and also doesn't maintain the benefits that GitHub offers such as an easily-accessible community and hooks into Coverity.

2. Small-time hosted repositories are more vulnerable to DDoS and other attacks; both of which impede development.

3. Substantial work has been done here in terms of housekeeping. Without more motive, moving all of that to another repository is a waste of time.

4. Most important: public disclosure. Every pull request and comment is guaranteed public in a non-private GitHub repository. If we used a private, non-GitHub, instance, we have the ability to *abuse* our ability to censor or rewrite history. Public disclosure also allows problem contributors to become subject to public shaming. This reduces the troll count and produces better software.

I'm sure there are more reasons to *not* make the code accessible via I2P only (as the ticket title implies) but 4 reasons are enough and we have more important concerns to focus on. For now, I see that GitHub does a great job for what we need.

**Comment by EinMByte** [comment]
I'd stick to Github for now, mainly because I think we'll get more contributions.

**Comment by anonimal** [comment]
Re: the 1st half of my point 1., GitHub's OAuth apparently *can* go [GitHub -> GitLab](http://doc.gitlab.com/ce/integration/github.html) - though, I still stand with the remainder of 1. and remaining points.

**Comment by fluffypony** [comment]
Guys it's not branching away, it's a mirror. GitHub remains the primary, the GitLab mirror would be a backup and would provide a failsafe if GitHub ever went down or removed the repo. Nobody is suggesting we move to GitLab:)

**Comment by anonimal** [comment]
> Source code accessability via I2P only

The title implies differently. Changing title to avoid confusion.

**Comment by anonimal** [comment]
```
2016-05-22  meeting-bot [fluffypony] 90 will happen automagically when our GitLab mirror is up
2016-05-22  meeting-bot [fluffypony] it'll have clearnet / Tor / i2p mirrors
2016-05-22  &anonimal Ok then. I've missed any discussions about that in the past, is there an ETA?
2016-05-22  meeting-bot [fluffypony] not at the moment - it's one of those "on the list" things, I lack the time to knuckle down and do it
2016-05-22  meeting-bot [fluffypony] we need a devops team :-P
2016-05-22  &anonimal Indeed. Ok, I'll add a note in ticket.
2016-05-22  &anonimal To whom should we assign #90 then?
2016-05-22  meeting-bot [fluffypony] me
2016-05-22  &anonimal Ok, will do.
```

**Comment by danrmiller** [comment]
You can reach the mirror using I2P at http://rrhjp2h4665m2vydnqetyz7h4ic267woyneguczbz572nmtygzza.b32.i2p/monero-project/kovri 
(http://monero-repo.i2p/monero-project/kovri)
You should be able to clone using git over http via i2p, but the repo address box displays the regular clear-internet dns name for the mirror repo.

I'll compile nginx with the sub_filter module enabled and try just replacing that string with the i2p address when its accessed over i2p.

I haven't tested git over http over i2p, try git clone http://monero-repo.i2p/monero-project/kovri.git

**Comment by anonimal** [comment]
Thanks @danrmiller! I'll take any further related-issues to https://github.com/monero-project/meta/issues/9.
