### ISSUE TITLE
Add option for for log directory

### ISSUE THREAD

**Issue by Wuodan** [monero-project/kovri#903]
---
**By submitting this issue, I confirm the following:**

- I have read and understood the developer guide in [kovri-docs](https://github.com/monero-project/kovri-docs).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.
---
By default, kovri writes logs to the directory  ~/.kovri/log in form of a file per day.
One can specify an alternative path with --log-file-name, but that will always be the same file name.

I would like the possibility to specify a folder path, where a log file per day is created.

Possible solutions:
a) Rename  --log-file-name to --log-path. If it's a file, write to that file. If it's a folder, create a file per day there.
b) An additional option --log-folder. Incompatible with --log-file-name.
(These are just ideas!!)

**Comment by coneiric** [comment]
> An additional option --log-folder. Incompatible with --log-file-name.

Just speaking for myself, two command-line options seem like a better solution. That way a user can specify custom directory and filename independently.

Why would the two options need to be incompatible?

**Comment by anonimal** [comment]
>Why would the two options need to be incompatible?

Because a filename could contain a path. I personally wouldn't bother with the work involved to sanitize filename and instead would opt for a single `--log-dir` option.

**Comment by anonimal** [comment]
NOTICE: THIS ISSUE HAS BEEN MOVED TO GitLab. Please continue the discussion there. See https://github.com/monero-project/kovri/issues/1013 for details.
