### ISSUE TITLE
kovri ELF contains insecure runpaths

### ISSUE THREAD

**Issue by Wuodan** [monero-project/kovri#904]
---
**By submitting this issue, I confirm the following:**

- I have read and understood the developer guide in [kovri-docs](https://github.com/monero-project/kovri-docs).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.
---
**Issue description:**
I'm running 'make release' with Gentoos package manager (portage).
When installing the kovri binary, portage compains about insecure runpaths. See the bottom of the attached build log.
[kovri-insecure_rpath-build.log.gz](https://github.com/monero-project/kovri/files/2099387/kovri-insecure_rpath-build.log.gz)

**My findings:**
a) scanelf --rpath
Portage complains during install phase, where the binary is copied from 
[build-dir]/homedir/bin/kovri to
[build-dir]/image/usr/bin/kovri
scanelf --rpath shows this difference:

> scanelf --rpath homedir/bin/kovri image/usr/bin/kovri
>  TYPE   RPATH FILE 
> ET_DYN /var/tmp/portage/net-vpn/kovri-9999/work/kovri-9999/deps/cryptopp homedir/bin/kovri 
> ET_DYN   -   image/usr/bin/kovri 

b) kovri-submoduled crypto++ vs. Gentoos dev-libs/crypto++ v7.0.0
When using Gentoos dev-libs/crypto++ v7.0.0 instead of the submoduled deps/cryptopp, the warning does not occur. (dev-libs/crypto++ v7.0.0 and the submoduled deps/cryptopp are identical.)
The build-instructions for crypto++
https://data.gpo.zugaina.org/gentoo/dev-libs/crypto++/crypto++-7.0.0-r2.ebuild
set some interesting variables:

> export CXX="$(tc-getCXX)"
> export LIBDIR="${EPREFIX}/usr/$(get_libdir)"
> export PREFIX="${EPREFIX}/usr"

Maybe similar settings during kovri build would resolve the rpath issue (wild guess)

**Comment by Wuodan** [comment]
c) does not occur with make release-static
... but for that I have to install static-libraries for boost and openssl ... and disable zlib for openssl (probably not kovri-related)

**Comment by anonimal** [comment]
>c) does not occur with make release-static

And it won't, because this is a dynamic build concern.

**Comment by anonimal** [comment]
@Wuodan can you `$ git fetch upstream pull/905/head:905 && git checkout 905 && make release && objdump -p -d ./build/kovri | grep -i rpath` in addition to testing your gentoo package against #905?

**Comment by Wuodan** [comment]
Looks good here:

- `objdump -p -d ./build/kovri | grep -i rpath` is empty after `make release`
- Gentoos package manager no longer complains about insecure rpaths

Thanks a lot!
